// ─────────────────────────────────────────────────────────────
// Education sub-app content: a Duolingo-style language course
// engine. COURSES holds hand-verified beginner content written
// from English into each target language. LANGUAGE_CATALOG lists
// every language on Earth the app knows about — courses that are
// fully playable are marked available: true, the rest appear in
// the catalog as "coming soon".
// ─────────────────────────────────────────────────────────────

// All languages of Earth (representative catalog). `available`
// means a hand-seeded course exists below.
const LANGUAGE_CATALOG = [
    { id: "spanish",      name: "Spanish",     nativeName: "Español",        flag: "🇪🇸", hl: "es",  rtl: false },
    { id: "french",       name: "French",      nativeName: "Français",       flag: "🇫🇷", hl: "fr",  rtl: false },
    { id: "german",       name: "German",      nativeName: "Deutsch",        flag: "🇩🇪", hl: "de",  rtl: false },
    { id: "italian",      name: "Italian",     nativeName: "Italiano",       flag: "🇮🇹", hl: "it",  rtl: false },
    { id: "portuguese",   name: "Portuguese",  nativeName: "Português",      flag: "🇧🇷", hl: "pt",  rtl: false },
    { id: "dutch",        name: "Dutch",       nativeName: "Nederlands",     flag: "🇳🇱", hl: "nl",  rtl: false },
    { id: "swedish",      name: "Swedish",     nativeName: "Svenska",        flag: "🇸🇪", hl: "sv",  rtl: false },
    { id: "japanese",     name: "Japanese",    nativeName: "日本語",          flag: "🇯🇵", hl: "ja",  rtl: false },
    { id: "korean",       name: "Korean",      nativeName: "한국어",          flag: "🇰🇷", hl: "ko",  rtl: false },
    { id: "mandarin",     name: "Mandarin",    nativeName: "中文",            flag: "🇨🇳", hl: "zh",  rtl: false },
    { id: "hindi",        name: "Hindi",       nativeName: "हिन्दी",          flag: "🇮🇳", hl: "hi",  rtl: false },
    { id: "arabic",       name: "Arabic",      nativeName: "العربية",        flag: "🇸🇦", hl: "ar",  rtl: true  },
    { id: "russian",      name: "Russian",     nativeName: "Русский",        flag: "🇷🇺", hl: "ru",  rtl: false },
    { id: "turkish",      name: "Turkish",     nativeName: "Türkçe",         flag: "🇹🇷", hl: "tr",  rtl: false },
    { id: "greek",        name: "Greek",       nativeName: "Ελληνικά",       flag: "🇬🇷", hl: "el",  rtl: false },
    { id: "hebrew",       name: "Hebrew",      nativeName: "עברית",          flag: "🇮🇱", hl: "he",  rtl: true  },
    { id: "polish",       name: "Polish",      nativeName: "Polski",         flag: "🇵🇱", hl: "pl",  rtl: false },
    { id: "danish",       name: "Danish",      nativeName: "Dansk",          flag: "🇩🇰", hl: "da",  rtl: false },
    { id: "norwegian",    name: "Norwegian",   nativeName: "Norsk",          flag: "🇳🇴", hl: "no",  rtl: false },
    { id: "finnish",      name: "Finnish",     nativeName: "Suomi",          flag: "🇫🇮", hl: "fi",  rtl: false },
    { id: "indonesian",   name: "Indonesian",  nativeName: "Bahasa Indonesia", flag: "🇮🇩", hl: "id", rtl: false },
    { id: "vietnamese",   name: "Vietnamese",  nativeName: "Tiếng Việt",     flag: "🇻🇳", hl: "vi",  rtl: false },
    { id: "thai",         name: "Thai",        nativeName: "ไทย",            flag: "🇹🇭", hl: "th",  rtl: false },
    { id: "ukrainian",    name: "Ukrainian",   nativeName: "Українська",     flag: "🇺🇦", hl: "uk",  rtl: false },
    { id: "czech",        name: "Czech",       nativeName: "Čeština",        flag: "🇨🇿", hl: "cs",  rtl: false },
    { id: "romanian",     name: "Romanian",    nativeName: "Română",         flag: "🇷🇴", hl: "ro",  rtl: false },
    { id: "hungarian",    name: "Hungarian",   nativeName: "Magyar",         flag: "🇭🇺", hl: "hu",  rtl: false },
    { id: "catalan",      name: "Catalan",     nativeName: "Català",         flag: "🇦🇩", hl: "ca",  rtl: false },
    { id: "swahili",      name: "Swahili",     nativeName: "Kiswahili",      flag: "🇰🇪", hl: "sw",  rtl: false },
    { id: "afrikaans",    name: "Afrikaans",   nativeName: "Afrikaans",      flag: "🇿🇦", hl: "af",  rtl: false },
    { id: "tagalog",      name: "Tagalog",     nativeName: "Tagalog",        flag: "🇵🇭", hl: "tl",  rtl: false },
    { id: "malay",        name: "Malay",       nativeName: "Bahasa Melayu",  flag: "🇲🇾", hl: "ms",  rtl: false },
    { id: "persian",      name: "Persian",     nativeName: "فارسی",          flag: "🇮🇷", hl: "fa",  rtl: true  },
    { id: "urdu",         name: "Urdu",        nativeName: "اردو",           flag: "🇵🇰", hl: "ur",  rtl: true  },
    { id: "bengali",      name: "Bengali",     nativeName: "বাংলা",          flag: "🇧🇩", hl: "bn",  rtl: false },
    { id: "tamil",        name: "Tamil",       nativeName: "தமிழ்",          flag: "🇮🇳", hl: "ta",  rtl: false },
    { id: "telugu",       name: "Telugu",      nativeName: "తెలుగు",         flag: "🇮🇳", hl: "te",  rtl: false },
    { id: "marathi",      name: "Marathi",     nativeName: "मराठी",          flag: "🇮🇳", hl: "mr",  rtl: false },
    { id: "gujarati",     name: "Gujarati",    nativeName: "ગુજરાતી",        flag: "🇮🇳", hl: "gu",  rtl: false },
    { id: "punjabi",      name: "Punjabi",     nativeName: "ਪੰਜਾਬੀ",         flag: "🇮🇳", hl: "pa",  rtl: false },
    { id: "sinhala",      name: "Sinhala",     nativeName: "සිංහල",          flag: "🇱🇰", hl: "si",  rtl: false },
    { id: "khmer",        name: "Khmer",       nativeName: "ខ្មែរ",           flag: "🇰🇭", hl: "km",  rtl: false },
    { id: "burmese",      name: "Burmese",     nativeName: "မြန်မာ",         flag: "🇲🇲", hl: "my",  rtl: false },
    { id: "lao",          name: "Lao",         nativeName: "ລາວ",            flag: "🇱🇦", hl: "lo",  rtl: false },
    { id: "nepali",       name: "Nepali",      nativeName: "नेपाली",          flag: "🇳🇵", hl: "ne",  rtl: false },
    { id: "mongolian",    name: "Mongolian",   nativeName: "Монгол",         flag: "🇲🇳", hl: "mn",  rtl: false },
    { id: "kazakh",       name: "Kazakh",      nativeName: "Қазақша",        flag: "🇰🇿", hl: "kk",  rtl: false },
    { id: "uzbek",        name: "Uzbek",       nativeName: "Oʻzbekcha",      flag: "🇺🇿", hl: "uz",  rtl: false },
    { id: "azerbaijani",  name: "Azerbaijani", nativeName: "Azərbaycanca",  flag: "🇦🇿", hl: "az",  rtl: false },
    { id: "georgian",     name: "Georgian",    nativeName: "ქართული",        flag: "🇬🇪", hl: "ka",  rtl: false },
    { id: "armenian",     name: "Armenian",    nativeName: "Հայերեն",        flag: "🇦🇲", hl: "hy",  rtl: false },
    { id: "amharic",      name: "Amharic",     nativeName: "አማርኛ",          flag: "🇪🇹", hl: "am",  rtl: false },
    { id: "somali",       name: "Somali",      nativeName: "Soomaali",       flag: "🇸🇴", hl: "so",  rtl: false },
    { id: "yoruba",       name: "Yoruba",      nativeName: "Yorùbá",         flag: "🇳🇬", hl: "yo",  rtl: false },
    { id: "hausa",        name: "Hausa",       nativeName: "Hausa",          flag: "🇳🇬", hl: "ha",  rtl: false },
    { id: "zulu",         name: "Zulu",        nativeName: "isiZulu",        flag: "🇿🇦", hl: "zu",  rtl: false },
    { id: "igbo",         name: "Igbo",        nativeName: "Asụsụ Igbo",     flag: "🇳🇬", hl: "ig",  rtl: false },
    { id: "esperanto",    name: "Esperanto",   nativeName: "Esperanto",      flag: "🌍", hl: "eo",  rtl: false },
    { id: "klingon",      name: "Klingon",     nativeName: "tlhIngan Hol",   flag: "🖖", hl: "tlh", rtl: false },
];

// Vocabulary entry -> [english, target, emoji]
// Phrase entry     -> [english, target]

const BASIC_LESSON = {
    basics: {
        title: "Basics",
        vocab: [
            ["hello", "", "👋"], ["thank you", "", "🙏"], ["yes", "", "👍"],
            ["no", "", "👎"], ["please", "", "🤲"], ["goodbye", "", "👋"],
            ["man", "", "👨"], ["woman", "", "👩"], ["boy", "", "👦"], ["girl", "", "👧"],
        ],
        phrases: [["hello, how are you?", ""], ["goodbye, my friend", ""]],
    },
    greetings: {
        title: "Greetings",
        vocab: [
            ["good morning", "", "🌅"], ["good night", "", "🌙"], ["good afternoon", "", "🌞"],
            ["how are you?", "", "🤗"], ["I'm fine", "", "😊"], ["see you later", "", "👋"],
            ["friend", "", "🧑‍🤝‍🧑"], ["family", "", "👨‍👩‍👧‍👦"], ["love", "", "❤️"], ["welcome", "", "🛬"],
        ],
        phrases: [["good morning, how are you?", ""], ["I love my family", ""]],
    },
    friends: {
        title: "Friends",
        vocab: [
            ["friend", "", "🧑‍🤝‍🧑"], ["home", "", "🏠"], ["water", "", "💧"], ["food", "", "🍽️"],
            ["eat", "", "😋"], ["drink", "", "🥤"], ["cat", "", "🐱"], ["dog", "", "🐶"], ["happy", "", "😃"], ["sad", "", "😢"],
        ],
        phrases: [["the cat drinks water", ""], ["we are happy", ""]],
    },
    travel: {
        title: "Travel",
        vocab: [
            ["airport", "", "🛫"], ["train", "", "🚆"], ["hotel", "", "🏨"], ["taxi", "", "🚕"],
            ["ticket", "", "🎫"], ["passport", "", "🛂"], ["map", "", "🗺️"], ["car", "", "🚗"], ["bus", "", "🚌"], ["street", "", "🛣️"],
        ],
        phrases: [["where is the hotel?", ""], ["I have one ticket", ""]],
    },
    food: {
        title: "Food",
        vocab: [
            ["bread", "", "🍞"], ["coffee", "", "☕"], ["milk", "", "🥛"], ["apple", "", "🍎"],
            ["rice", "", "🍚"], ["meat", "", "🥩"], ["tea", "", "🍵"], ["egg", "", "🥚"], ["water", "", "💧"], ["banana", "", "🍌"],
        ],
        phrases: [["I drink coffee in the morning", ""], ["the bread and the egg are good", ""]],
    },
    numbers: {
        title: "Numbers",
        vocab: [
            ["one", "", "1️⃣"], ["two", "", "2️⃣"], ["three", "", "3️⃣"], ["four", "", "4️⃣"],
            ["five", "", "5️⃣"], ["six", "", "6️⃣"], ["seven", "", "7️⃣"], ["eight", "", "8️⃣"],
            ["nine", "", "9️⃣"], ["ten", "", "🔟"],
        ],
        phrases: [["I have two cats", ""], ["there are three apples", ""]],
    },
    colors: {
        title: "Colors",
        vocab: [
            ["red", "", "🔴"], ["blue", "", "🔵"], ["green", "", "🟢"], ["yellow", "", "🟡"],
            ["white", "", "⚪"], ["black", "", "⚫"], ["purple", "", "🟣"], ["orange", "", "🟠"], ["pink", "", "🩷"], ["brown", "", "🟤"],
        ],
        phrases: [["the flower is red", ""], ["the sky is blue", ""]],
    },
    people: {
        title: "People",
        vocab: [
            ["mother", "", "👩"], ["father", "", "👨"], ["sister", "", "👧"], ["brother", "", "👦"],
            ["son", "", "👶"], ["daughter", "", "🎀"], ["teacher", "", "🧑‍🏫"], ["doctor", "", "🧑‍⚕️"], ["child", "", "🧒"], ["baby", "", "🍼"],
        ],
        phrases: [["my mother is a doctor", ""], ["the teacher is my friend", ""]],
    },
};

// Per-language translation map: lessonId -> [english, target]
const TRANSLATIONS = {
    spanish: {
        basics:      [["hello", "hola"], ["thank you", "gracias"], ["yes", "sí"], ["no", "no"], ["please", "por favor"], ["goodbye", "adiós"], ["man", "hombre"], ["woman", "mujer"], ["boy", "niño"], ["girl", "niña"]],
        greetings:   [["good morning", "buenos días"], ["good night", "buenas noches"], ["good afternoon", "buenas tardes"], ["how are you?", "¿cómo estás?"], ["I'm fine", "estoy bien"], ["see you later", "hasta luego"], ["friend", "amigo"], ["family", "familia"], ["love", "amor"], ["welcome", "bienvenido"]],
        friends:     [["friend", "amigo"], ["home", "casa"], ["water", "agua"], ["food", "comida"], ["eat", "comer"], ["drink", "beber"], ["cat", "gato"], ["dog", "perro"], ["happy", "feliz"], ["sad", "triste"]],
        travel:      [["airport", "aeropuerto"], ["train", "tren"], ["hotel", "hotel"], ["taxi", "taxi"], ["ticket", "boleto"], ["passport", "pasaporte"], ["map", "mapa"], ["car", "coche"], ["bus", "autobús"], ["street", "calle"]],
        food:        [["bread", "pan"], ["coffee", "café"], ["milk", "leche"], ["apple", "manzana"], ["rice", "arroz"], ["meat", "carne"], ["tea", "té"], ["egg", "huevo"], ["water", "agua"], ["banana", "plátano"]],
        numbers:     [["one", "uno"], ["two", "dos"], ["three", "tres"], ["four", "cuatro"], ["five", "cinco"], ["six", "seis"], ["seven", "siete"], ["eight", "ocho"], ["nine", "nueve"], ["ten", "diez"]],
        colors:      [["red", "rojo"], ["blue", "azul"], ["green", "verde"], ["yellow", "amarillo"], ["white", "blanco"], ["black", "negro"], ["purple", "morado"], ["orange", "naranja"], ["pink", "rosa"], ["brown", "marrón"]],
        people:      [["mother", "madre"], ["father", "padre"], ["sister", "hermana"], ["brother", "hermano"], ["son", "hijo"], ["daughter", "hija"], ["teacher", "maestro"], ["doctor", "doctor"], ["child", "niño"], ["baby", "bebé"]],
        _phrases: {
            basics: [["hello, how are you?", "hola, ¿cómo estás?"], ["goodbye, my friend", "adiós, mi amigo"]],
            greetings: [["good morning, how are you?", "buenos días, ¿cómo estás?"], ["I love my family", "amo a mi familia"]],
            friends: [["the cat drinks water", "el gato bebe agua"], ["we are happy", "somos felices"]],
            travel: [["where is the hotel?", "¿dónde está el hotel?"], ["I have one ticket", "tengo un boleto"]],
            food: [["I drink coffee in the morning", "tomo café en la mañana"], ["the bread and the egg are good", "el pan y el huevo son buenos"]],
            numbers: [["I have two cats", "tengo dos gatos"], ["there are three apples", "hay tres manzanas"]],
            colors: [["the flower is red", "la flor es roja"], ["the sky is blue", "el cielo es azul"]],
            people: [["my mother is a doctor", "mi madre es doctora"], ["the teacher is my friend", "el maestro es mi amigo"]],
        },
    },
    french: {
        basics:      [["hello", "bonjour"], ["thank you", "merci"], ["yes", "oui"], ["no", "non"], ["please", "s'il vous plaît"], ["goodbye", "au revoir"], ["man", "homme"], ["woman", "femme"], ["boy", "garçon"], ["girl", "fille"]],
        greetings:   [["good morning", "bonjour"], ["good night", "bonne nuit"], ["good afternoon", "bon après-midi"], ["how are you?", "comment ça va ?"], ["I'm fine", "je vais bien"], ["see you later", "à plus tard"], ["friend", "ami"], ["family", "famille"], ["love", "amour"], ["welcome", "bienvenue"]],
        friends:     [["friend", "ami"], ["home", "maison"], ["water", "eau"], ["food", "nourriture"], ["eat", "manger"], ["drink", "boire"], ["cat", "chat"], ["dog", "chien"], ["happy", "heureux"], ["sad", "triste"]],
        travel:      [["airport", "aéroport"], ["train", "train"], ["hotel", "hôtel"], ["taxi", "taxi"], ["ticket", "billet"], ["passport", "passeport"], ["map", "carte"], ["car", "voiture"], ["bus", "bus"], ["street", "rue"]],
        food:        [["bread", "pain"], ["coffee", "café"], ["milk", "lait"], ["apple", "pomme"], ["rice", "riz"], ["meat", "viande"], ["tea", "thé"], ["egg", "œuf"], ["water", "eau"], ["banana", "banane"]],
        numbers:     [["one", "un"], ["two", "deux"], ["three", "trois"], ["four", "quatre"], ["five", "cinq"], ["six", "six"], ["seven", "sept"], ["eight", "huit"], ["nine", "neuf"], ["ten", "dix"]],
        colors:      [["red", "rouge"], ["blue", "bleu"], ["green", "vert"], ["yellow", "jaune"], ["white", "blanc"], ["black", "noir"], ["purple", "violet"], ["orange", "orange"], ["pink", "rose"], ["brown", "marron"]],
        people:      [["mother", "mère"], ["father", "père"], ["sister", "sœur"], ["brother", "frère"], ["son", "fils"], ["daughter", "fille"], ["teacher", "professeur"], ["doctor", "médecin"], ["child", "enfant"], ["baby", "bébé"]],
        _phrases: {
            basics: [["hello, how are you?", "bonjour, comment ça va ?"], ["goodbye, my friend", "au revoir, mon ami"]],
            greetings: [["good morning, how are you?", "bonjour, comment allez-vous ?"], ["I love my family", "j'aime ma famille"]],
            friends: [["the cat drinks water", "le chat boit de l'eau"], ["we are happy", "nous sommes heureux"]],
            travel: [["where is the hotel?", "où est l'hôtel ?"], ["I have one ticket", "j'ai un billet"]],
            food: [["I drink coffee in the morning", "je bois du café le matin"], ["the bread and the egg are good", "le pain et l'œuf sont bons"]],
            numbers: [["I have two cats", "j'ai deux chats"], ["there are three apples", "il y a trois pommes"]],
            colors: [["the flower is red", "la fleur est rouge"], ["the sky is blue", "le ciel est bleu"]],
            people: [["my mother is a doctor", "ma mère est médecin"], ["the teacher is my friend", "le professeur est mon ami"]],
        },
    },
    german: {
        basics:      [["hello", "hallo"], ["thank you", "danke"], ["yes", "ja"], ["no", "nein"], ["please", "bitte"], ["goodbye", "tschüss"], ["man", "Mann"], ["woman", "Frau"], ["boy", "Junge"], ["girl", "Mädchen"]],
        greetings:   [["good morning", "guten Morgen"], ["good night", "gute Nacht"], ["good afternoon", "guten Tag"], ["how are you?", "wie geht es dir?"], ["I'm fine", "mir geht es gut"], ["see you later", "bis später"], ["friend", "Freund"], ["family", "Familie"], ["love", "Liebe"], ["welcome", "willkommen"]],
        friends:     [["friend", "Freund"], ["home", "Zuhause"], ["water", "Wasser"], ["food", "Essen"], ["eat", "essen"], ["drink", "trinken"], ["cat", "Katze"], ["dog", "Hund"], ["happy", "glücklich"], ["sad", "traurig"]],
        travel:      [["airport", "Flughafen"], ["train", "Zug"], ["hotel", "Hotel"], ["taxi", "Taxi"], ["ticket", "Fahrkarte"], ["passport", "Reisepass"], ["map", "Karte"], ["car", "Auto"], ["bus", "Bus"], ["street", "Straße"]],
        food:        [["bread", "Brot"], ["coffee", "Kaffee"], ["milk", "Milch"], ["apple", "Apfel"], ["rice", "Reis"], ["meat", "Fleisch"], ["tea", "Tee"], ["egg", "Ei"], ["water", "Wasser"], ["banana", "Banane"]],
        numbers:     [["one", "eins"], ["two", "zwei"], ["three", "drei"], ["four", "vier"], ["five", "fünf"], ["six", "sechs"], ["seven", "sieben"], ["eight", "acht"], ["nine", "neun"], ["ten", "zehn"]],
        colors:      [["red", "rot"], ["blue", "blau"], ["green", "grün"], ["yellow", "gelb"], ["white", "weiß"], ["black", "schwarz"], ["purple", "lila"], ["orange", "orange"], ["pink", "rosa"], ["brown", "braun"]],
        people:      [["mother", "Mutter"], ["father", "Vater"], ["sister", "Schwester"], ["brother", "Bruder"], ["son", "Sohn"], ["daughter", "Tochter"], ["teacher", "Lehrer"], ["doctor", "Arzt"], ["child", "Kind"], ["baby", "Baby"]],
        _phrases: {
            basics: [["hello, how are you?", "hallo, wie geht es dir?"], ["goodbye, my friend", "tschüss, mein Freund"]],
            greetings: [["good morning, how are you?", "guten Morgen, wie geht es dir?"], ["I love my family", "ich liebe meine Familie"]],
            friends: [["the cat drinks water", "die Katze trinkt Wasser"], ["we are happy", "wir sind glücklich"]],
            travel: [["where is the hotel?", "wo ist das Hotel?"], ["I have one ticket", "ich habe eine Fahrkarte"]],
            food: [["I drink coffee in the morning", "ich trinke morgens Kaffee"], ["the bread and the egg are good", "das Brot und das Ei sind gut"]],
            numbers: [["I have two cats", "ich habe zwei Katzen"], ["there are three apples", "es gibt drei Äpfel"]],
            colors: [["the flower is red", "die Blume ist rot"], ["the sky is blue", "der Himmel ist blau"]],
            people: [["my mother is a doctor", "meine Mutter ist Ärztin"], ["the teacher is my friend", "der Lehrer ist mein Freund"]],
        },
    },
    italian: {
        basics:      [["hello", "ciao"], ["thank you", "grazie"], ["yes", "sì"], ["no", "no"], ["please", "per favore"], ["goodbye", "arrivederci"], ["man", "uomo"], ["woman", "donna"], ["boy", "ragazzo"], ["girl", "ragazza"]],
        greetings:   [["good morning", "buongiorno"], ["good night", "buonanotte"], ["good afternoon", "buon pomeriggio"], ["how are you?", "come stai?"], ["I'm fine", "sto bene"], ["see you later", "a più tardi"], ["friend", "amico"], ["family", "famiglia"], ["love", "amore"], ["welcome", "benvenuto"]],
        friends:     [["friend", "amico"], ["home", "casa"], ["water", "acqua"], ["food", "cibo"], ["eat", "mangiare"], ["drink", "bere"], ["cat", "gatto"], ["dog", "cane"], ["happy", "felice"], ["sad", "triste"]],
        travel:      [["airport", "aeroporto"], ["train", "treno"], ["hotel", "albergo"], ["taxi", "taxi"], ["ticket", "biglietto"], ["passport", "passaporto"], ["map", "mappa"], ["car", "macchina"], ["bus", "autobus"], ["street", "strada"]],
        food:        [["bread", "pane"], ["coffee", "caffè"], ["milk", "latte"], ["apple", "mela"], ["rice", "riso"], ["meat", "carne"], ["tea", "tè"], ["egg", "uovo"], ["water", "acqua"], ["banana", "banana"]],
        numbers:     [["one", "uno"], ["two", "due"], ["three", "tre"], ["four", "quattro"], ["five", "cinque"], ["six", "sei"], ["seven", "sette"], ["eight", "otto"], ["nine", "nove"], ["ten", "dieci"]],
        colors:      [["red", "rosso"], ["blue", "blu"], ["green", "verde"], ["yellow", "giallo"], ["white", "bianco"], ["black", "nero"], ["purple", "viola"], ["orange", "arancione"], ["pink", "rosa"], ["brown", "marrone"]],
        people:      [["mother", "madre"], ["father", "padre"], ["sister", "sorella"], ["brother", "fratello"], ["son", "figlio"], ["daughter", "figlia"], ["teacher", "insegnante"], ["doctor", "medico"], ["child", "bambino"], ["baby", "bambino"]],
        _phrases: {
            basics: [["hello, how are you?", "ciao, come stai?"], ["goodbye, my friend", "arrivederci, amico mio"]],
            greetings: [["good morning, how are you?", "buongiorno, come stai?"], ["I love my family", "amo la mia famiglia"]],
            friends: [["the cat drinks water", "il gatto beve acqua"], ["we are happy", "siamo felici"]],
            travel: [["where is the hotel?", "dov'è l'albergo?"], ["I have one ticket", "ho un biglietto"]],
            food: [["I drink coffee in the morning", "bevo il caffè la mattina"], ["the bread and the egg are good", "il pane e l'uovo sono buoni"]],
            numbers: [["I have two cats", "ho due gatti"], ["there are three apples", "ci sono tre mele"]],
            colors: [["the flower is red", "il fiore è rosso"], ["the sky is blue", "il cielo è blu"]],
            people: [["my mother is a doctor", "mia madre è medico"], ["the teacher is my friend", "l'insegnante è mio amico"]],
        },
    },
    portuguese: {
        basics:      [["hello", "olá"], ["thank you", "obrigado"], ["yes", "sim"], ["no", "não"], ["please", "por favor"], ["goodbye", "tchau"], ["man", "homem"], ["woman", "mulher"], ["boy", "menino"], ["girl", "menina"]],
        greetings:   [["good morning", "bom dia"], ["good night", "boa noite"], ["good afternoon", "boa tarde"], ["how are you?", "como você está?"], ["I'm fine", "estou bem"], ["see you later", "até mais"], ["friend", "amigo"], ["family", "família"], ["love", "amor"], ["welcome", "bem-vindo"]],
        friends:     [["friend", "amigo"], ["home", "casa"], ["water", "água"], ["food", "comida"], ["eat", "comer"], ["drink", "beber"], ["cat", "gato"], ["dog", "cachorro"], ["happy", "feliz"], ["sad", "triste"]],
        travel:      [["airport", "aeroporto"], ["train", "trem"], ["hotel", "hotel"], ["taxi", "táxi"], ["ticket", "bilhete"], ["passport", "passaporte"], ["map", "mapa"], ["car", "carro"], ["bus", "ônibus"], ["street", "rua"]],
        food:        [["bread", "pão"], ["coffee", "café"], ["milk", "leite"], ["apple", "maçã"], ["rice", "arroz"], ["meat", "carne"], ["tea", "chá"], ["egg", "ovo"], ["water", "água"], ["banana", "banana"]],
        numbers:     [["one", "um"], ["two", "dois"], ["three", "três"], ["four", "quatro"], ["five", "cinco"], ["six", "seis"], ["seven", "sete"], ["eight", "oito"], ["nine", "nove"], ["ten", "dez"]],
        colors:      [["red", "vermelho"], ["blue", "azul"], ["green", "verde"], ["yellow", "amarelo"], ["white", "branco"], ["black", "preto"], ["purple", "roxo"], ["orange", "laranja"], ["pink", "rosa"], ["brown", "marrom"]],
        people:      [["mother", "mãe"], ["father", "pai"], ["sister", "irmã"], ["brother", "irmão"], ["son", "filho"], ["daughter", "filha"], ["teacher", "professor"], ["doctor", "médico"], ["child", "criança"], ["baby", "bebê"]],
        _phrases: {
            basics: [["hello, how are you?", "olá, como você está?"], ["goodbye, my friend", "tchau, meu amigo"]],
            greetings: [["good morning, how are you?", "bom dia, como você está?"], ["I love my family", "eu amo a minha família"]],
            friends: [["the cat drinks water", "o gato bebe água"], ["we are happy", "estamos felizes"]],
            travel: [["where is the hotel?", "onde fica o hotel?"], ["I have one ticket", "eu tenho um bilhete"]],
            food: [["I drink coffee in the morning", "eu tomo café de manhã"], ["the bread and the egg are good", "o pão e o ovo são bons"]],
            numbers: [["I have two cats", "eu tenho dois gatos"], ["there are three apples", "há três maçãs"]],
            colors: [["the flower is red", "a flor é vermelha"], ["the sky is blue", "o céu é azul"]],
            people: [["my mother is a doctor", "minha mãe é médica"], ["the teacher is my friend", "o professor é meu amigo"]],
        },
    },
    dutch: {
        basics:      [["hello", "hallo"], ["thank you", "dank je"], ["yes", "ja"], ["no", "nee"], ["please", "alsjeblieft"], ["goodbye", "tot ziens"], ["man", "man"], ["woman", "vrouw"], ["boy", "jongen"], ["girl", "meisje"]],
        greetings:   [["good morning", "goedemorgen"], ["good night", "goedenacht"], ["good afternoon", "goedemiddag"], ["how are you?", "hoe gaat het?"], ["I'm fine", "het gaat goed"], ["see you later", "tot later"], ["friend", "vriend"], ["family", "familie"], ["love", "liefde"], ["welcome", "welkom"]],
        friends:     [["friend", "vriend"], ["home", "thuis"], ["water", "water"], ["food", "eten"], ["eat", "eten"], ["drink", "drinken"], ["cat", "kat"], ["dog", "hond"], ["happy", "gelukkig"], ["sad", "verdrietig"]],
        travel:      [["airport", "luchthaven"], ["train", "trein"], ["hotel", "hotel"], ["taxi", "taxi"], ["ticket", "kaartje"], ["passport", "paspoort"], ["map", "kaart"], ["car", "auto"], ["bus", "bus"], ["street", "straat"]],
        food:        [["bread", "brood"], ["coffee", "koffie"], ["milk", "melk"], ["apple", "appel"], ["rice", "rijst"], ["meat", "vlees"], ["tea", "thee"], ["egg", "ei"], ["water", "water"], ["banana", "banaan"]],
        numbers:     [["one", "een"], ["two", "twee"], ["three", "drie"], ["four", "vier"], ["five", "vijf"], ["six", "zes"], ["seven", "zeven"], ["eight", "acht"], ["nine", "negen"], ["ten", "tien"]],
        colors:      [["red", "rood"], ["blue", "blauw"], ["green", "groen"], ["yellow", "geel"], ["white", "wit"], ["black", "zwart"], ["purple", "paars"], ["orange", "oranje"], ["pink", "roze"], ["brown", "bruin"]],
        people:      [["mother", "moeder"], ["father", "vader"], ["sister", "zus"], ["brother", "broer"], ["son", "zoon"], ["daughter", "dochter"], ["teacher", "leraar"], ["doctor", "dokter"], ["child", "kind"], ["baby", "baby"]],
        _phrases: {
            basics: [["hello, how are you?", "hallo, hoe gaat het?"], ["goodbye, my friend", "tot ziens, mijn vriend"]],
            greetings: [["good morning, how are you?", "goedemorgen, hoe gaat het?"], ["I love my family", "ik houd van mijn familie"]],
            friends: [["the cat drinks water", "de kat drinkt water"], ["we are happy", "wij zijn gelukkig"]],
            travel: [["where is the hotel?", "waar is het hotel?"], ["I have one ticket", "ik heb één kaartje"]],
            food: [["I drink coffee in the morning", "ik drink 's ochtends koffie"], ["the bread and the egg are good", "het brood en het ei zijn goed"]],
            numbers: [["I have two cats", "ik heb twee katten"], ["there are three apples", "er zijn drie appels"]],
            colors: [["the flower is red", "de bloem is rood"], ["the sky is blue", "de lucht is blauw"]],
            people: [["my mother is a doctor", "mijn moeder is dokter"], ["the teacher is my friend", "de leraar is mijn vriend"]],
        },
    },
    swedish: {
        basics:      [["hello", "hej"], ["thank you", "tack"], ["yes", "ja"], ["no", "nej"], ["please", "snälla"], ["goodbye", "hej då"], ["man", "man"], ["woman", "kvinna"], ["boy", "pojke"], ["girl", "flicka"]],
        greetings:   [["good morning", "god morgon"], ["good night", "god natt"], ["good afternoon", "god eftermiddag"], ["how are you?", "hur mår du?"], ["I'm fine", "jag mår bra"], ["see you later", "vi ses senare"], ["friend", "vän"], ["family", "familj"], ["love", "kärlek"], ["welcome", "välkommen"]],
        friends:     [["friend", "vän"], ["home", "hem"], ["water", "vatten"], ["food", "mat"], ["eat", "äta"], ["drink", "dricka"], ["cat", "katt"], ["dog", "hund"], ["happy", "glad"], ["sad", "ledsen"]],
        travel:      [["airport", "flygplats"], ["train", "tåg"], ["hotel", "hotell"], ["taxi", "taxi"], ["ticket", "biljett"], ["passport", "pass"], ["map", "karta"], ["car", "bil"], ["bus", "buss"], ["street", "gata"]],
        food:        [["bread", "bröd"], ["coffee", "kaffe"], ["milk", "mjölk"], ["apple", "äpple"], ["rice", "ris"], ["meat", "kött"], ["tea", "te"], ["egg", "ägg"], ["water", "vatten"], ["banana", "banan"]],
        numbers:     [["one", "ett"], ["two", "två"], ["three", "tre"], ["four", "fyra"], ["five", "fem"], ["six", "sex"], ["seven", "sju"], ["eight", "åtta"], ["nine", "nio"], ["ten", "tio"]],
        colors:      [["red", "röd"], ["blue", "blå"], ["green", "grön"], ["yellow", "gul"], ["white", "vit"], ["black", "svart"], ["purple", "lila"], ["orange", "orange"], ["pink", "rosa"], ["brown", "brun"]],
        people:      [["mother", "mamma"], ["father", "pappa"], ["sister", "syster"], ["brother", "bror"], ["son", "son"], ["daughter", "dotter"], ["teacher", "lärare"], ["doctor", "läkare"], ["child", "barn"], ["baby", "baby"]],
        _phrases: {
            basics: [["hello, how are you?", "hej, hur mår du?"], ["goodbye, my friend", "hej då, min vän"]],
            greetings: [["good morning, how are you?", "god morgon, hur mår du?"], ["I love my family", "jag älskar min familj"]],
            friends: [["the cat drinks water", "katten dricker vatten"], ["we are happy", "vi är glada"]],
            travel: [["where is the hotel?", "var ligger hotellet?"], ["I have one ticket", "jag har en biljett"]],
            food: [["I drink coffee in the morning", "jag dricker kaffe på morgonen"], ["the bread and the egg are good", "brödet och ägget är gott"]],
            numbers: [["I have two cats", "jag har två katter"], ["there are three apples", "det finns tre äpplen"]],
            colors: [["the flower is red", "blomman är röd"], ["the sky is blue", "himlen är blå"]],
            people: [["my mother is a doctor", "min mamma är läkare"], ["the teacher is my friend", "läraren är min vän"]],
        },
    },
    japanese: {
        basics:      [["hello", "こんにちは"], ["thank you", "ありがとう"], ["yes", "はい"], ["no", "いいえ"], ["please", "お願いします"], ["goodbye", "さようなら"], ["man", "男"], ["woman", "女"], ["boy", "男の子"], ["girl", "女の子"]],
        greetings:   [["good morning", "おはよう"], ["good night", "おやすみなさい"], ["good afternoon", "こんにちは"], ["how are you?", "元気ですか？"], ["I'm fine", "元気です"], ["see you later", "また後で"], ["friend", "友達"], ["family", "家族"], ["love", "愛"], ["welcome", "ようこそ"]],
        friends:     [["friend", "友達"], ["home", "家"], ["water", "水"], ["food", "食べ物"], ["eat", "食べる"], ["drink", "飲む"], ["cat", "猫"], ["dog", "犬"], ["happy", "嬉しい"], ["sad", "悲しい"]],
        travel:      [["airport", "空港"], ["train", "電車"], ["hotel", "ホテル"], ["taxi", "タクシー"], ["ticket", "切符"], ["passport", "パスポート"], ["map", "地図"], ["car", "車"], ["bus", "バス"], ["street", "道"]],
        food:        [["bread", "パン"], ["coffee", "コーヒー"], ["milk", "牛乳"], ["apple", "りんご"], ["rice", "ごはん"], ["meat", "肉"], ["tea", "お茶"], ["egg", "卵"], ["water", "水"], ["banana", "バナナ"]],
        numbers:     [["one", "いち"], ["two", "に"], ["three", "さん"], ["four", "よん"], ["five", "ご"], ["six", "ろく"], ["seven", "なな"], ["eight", "はち"], ["nine", "きゅう"], ["ten", "じゅう"]],
        colors:      [["red", "赤"], ["blue", "青"], ["green", "緑"], ["yellow", "黄色"], ["white", "白"], ["black", "黒"], ["purple", "紫"], ["orange", "オレンジ"], ["pink", "ピンク"], ["brown", "茶色"]],
        people:      [["mother", "母"], ["father", "父"], ["sister", "姉"], ["brother", "兄"], ["son", "息子"], ["daughter", "娘"], ["teacher", "先生"], ["doctor", "医者"], ["child", "子供"], ["baby", "赤ちゃん"]],
        _phrases: {
            basics: [["hello, how are you?", "こんにちは、お元気ですか？"], ["goodbye, my friend", "さようなら、私の友達"]],
            greetings: [["good morning, how are you?", "おはよう、お元気ですか？"], ["I love my family", "私は家族を愛しています"]],
            friends: [["the cat drinks water", "猫は水を飲みます"], ["we are happy", "私たちは幸せです"]],
            travel: [["where is the hotel?", "ホテルはどこですか？"], ["I have one ticket", "切符を一枚持っています"]],
            food: [["I drink coffee in the morning", "朝、コーヒーを飲みます"], ["the bread and the egg are good", "パンと卵はおいしいです"]],
            numbers: [["I have two cats", "猫を二匹飼っています"], ["there are three apples", "りんごが三つあります"]],
            colors: [["the flower is red", "花は赤いです"], ["the sky is blue", "空は青いです"]],
            people: [["my mother is a doctor", "母は医者です"], ["the teacher is my friend", "先生は私の友達です"]],
        },
    },
    korean: {
        basics:      [["hello", "안녕하세요"], ["thank you", "감사합니다"], ["yes", "네"], ["no", "아니요"], ["please", "주세요"], ["goodbye", "안녕히 가세요"], ["man", "남자"], ["woman", "여자"], ["boy", "소년"], ["girl", "소녀"]],
        greetings:   [["good morning", "좋은 아침"], ["good night", "안녕히 주무세요"], ["good afternoon", "좋은 오후"], ["how are you?", "어떻게 지내세요?"], ["I'm fine", "잘 지내요"], ["see you later", "나중에 봐요"], ["friend", "친구"], ["family", "가족"], ["love", "사랑"], ["welcome", "환영합니다"]],
        friends:     [["friend", "친구"], ["home", "집"], ["water", "물"], ["food", "음식"], ["eat", "먹다"], ["drink", "마시다"], ["cat", "고양이"], ["dog", "개"], ["happy", "행복한"], ["sad", "슬픈"]],
        travel:      [["airport", "공항"], ["train", "기차"], ["hotel", "호텔"], ["taxi", "택시"], ["ticket", "표"], ["passport", "여권"], ["map", "지도"], ["car", "자동차"], ["bus", "버스"], ["street", "거리"]],
        food:        [["bread", "빵"], ["coffee", "커피"], ["milk", "우유"], ["apple", "사과"], ["rice", "밥"], ["meat", "고기"], ["tea", "차"], ["egg", "계란"], ["water", "물"], ["banana", "바나나"]],
        numbers:     [["one", "하나"], ["two", "둘"], ["three", "셋"], ["four", "넷"], ["five", "다섯"], ["six", "여섯"], ["seven", "일곱"], ["eight", "여덟"], ["nine", "아홉"], ["ten", "열"]],
        colors:      [["red", "빨간색"], ["blue", "파란색"], ["green", "초록색"], ["yellow", "노란색"], ["white", "흰색"], ["black", "검은색"], ["purple", "보라색"], ["orange", "주황색"], ["pink", "분홍색"], ["brown", "갈색"]],
        people:      [["mother", "어머니"], ["father", "아버지"], ["sister", "언니"], ["brother", "형"], ["son", "아들"], ["daughter", "딸"], ["teacher", "선생님"], ["doctor", "의사"], ["child", "아이"], ["baby", "아기"]],
        _phrases: {
            basics: [["hello, how are you?", "안녕하세요, 어떻게 지내세요?"], ["goodbye, my friend", "안녕히 가세요, 내 친구"]],
            greetings: [["good morning, how are you?", "좋은 아침이에요, 어떻게 지내세요?"], ["I love my family", "나는 가족을 사랑해요"]],
            friends: [["the cat drinks water", "고양이가 물을 마셔요"], ["we are happy", "우리는 행복해요"]],
            travel: [["where is the hotel?", "호텔이 어디예요?"], ["I have one ticket", "표 한 장 있어요"]],
            food: [["I drink coffee in the morning", "아침에 커피를 마셔요"], ["the bread and the egg are good", "빵과 계란이 맛있어요"]],
            numbers: [["I have two cats", "고양이 두 마리가 있어요"], ["there are three apples", "사과 세 개가 있어요"]],
            colors: [["the flower is red", "꽃이 빨개요"], ["the sky is blue", "하늘이 파래요"]],
            people: [["my mother is a doctor", "어머니는 의사예요"], ["the teacher is my friend", "선생님은 제 친구예요"]],
        },
    },
    mandarin: {
        basics:      [["hello", "你好"], ["thank you", "谢谢"], ["yes", "是"], ["no", "不"], ["please", "请"], ["goodbye", "再见"], ["man", "男人"], ["woman", "女人"], ["boy", "男孩"], ["girl", "女孩"]],
        greetings:   [["good morning", "早上好"], ["good night", "晚安"], ["good afternoon", "下午好"], ["how are you?", "你好吗？"], ["I'm fine", "我很好"], ["see you later", "待会见"], ["friend", "朋友"], ["family", "家人"], ["love", "爱"], ["welcome", "欢迎"]],
        friends:     [["friend", "朋友"], ["home", "家"], ["water", "水"], ["food", "食物"], ["eat", "吃"], ["drink", "喝"], ["cat", "猫"], ["dog", "狗"], ["happy", "开心"], ["sad", "难过"]],
        travel:      [["airport", "机场"], ["train", "火车"], ["hotel", "酒店"], ["taxi", "出租车"], ["ticket", "票"], ["passport", "护照"], ["map", "地图"], ["car", "汽车"], ["bus", "公共汽车"], ["street", "街"]],
        food:        [["bread", "面包"], ["coffee", "咖啡"], ["milk", "牛奶"], ["apple", "苹果"], ["rice", "米饭"], ["meat", "肉"], ["tea", "茶"], ["egg", "鸡蛋"], ["water", "水"], ["banana", "香蕉"]],
        numbers:     [["one", "一"], ["two", "二"], ["three", "三"], ["four", "四"], ["five", "五"], ["six", "六"], ["seven", "七"], ["eight", "八"], ["nine", "九"], ["ten", "十"]],
        colors:      [["red", "红色"], ["blue", "蓝色"], ["green", "绿色"], ["yellow", "黄色"], ["white", "白色"], ["black", "黑色"], ["purple", "紫色"], ["orange", "橙色"], ["pink", "粉色"], ["brown", "棕色"]],
        people:      [["mother", "妈妈"], ["father", "爸爸"], ["sister", "姐姐"], ["brother", "哥哥"], ["son", "儿子"], ["daughter", "女儿"], ["teacher", "老师"], ["doctor", "医生"], ["child", "孩子"], ["baby", "婴儿"]],
        _phrases: {
            basics: [["hello, how are you?", "你好，你好吗？"], ["goodbye, my friend", "再见，我的朋友"]],
            greetings: [["good morning, how are you?", "早上好，你好吗？"], ["I love my family", "我爱我的家人"]],
            friends: [["the cat drinks water", "猫喝水"], ["we are happy", "我们很开心"]],
            travel: [["where is the hotel?", "酒店在哪里？"], ["I have one ticket", "我有一张票"]],
            food: [["I drink coffee in the morning", "我早上喝咖啡"], ["the bread and the egg are good", "面包和鸡蛋很好"]],
            numbers: [["I have two cats", "我有两只猫"], ["there are three apples", "有三个苹果"]],
            colors: [["the flower is red", "花是红色的"], ["the sky is blue", "天空是蓝色的"]],
            people: [["my mother is a doctor", "我妈妈是医生"], ["the teacher is my friend", "老师是我的朋友"]],
        },
    },
    hindi: {
        basics:      [["hello", "नमस्ते"], ["thank you", "धन्यवाद"], ["yes", "हाँ"], ["no", "नहीं"], ["please", "कृपया"], ["goodbye", "अलविदा"], ["man", "आदमी"], ["woman", "औरत"], ["boy", "लड़का"], ["girl", "लड़की"]],
        greetings:   [["good morning", "सुप्रभात"], ["good night", "शुभ रात्रि"], ["good afternoon", "नमस्कार"], ["how are you?", "आप कैसे हैं?"], ["I'm fine", "मैं ठीक हूँ"], ["see you later", "बाद में मिलते हैं"], ["friend", "दोस्त"], ["family", "परिवार"], ["love", "प्यार"], ["welcome", "स्वागत है"]],
        friends:     [["friend", "दोस्त"], ["home", "घर"], ["water", "पानी"], ["food", "खाना"], ["eat", "खाना"], ["drink", "पीना"], ["cat", "बिल्ली"], ["dog", "कुत्ता"], ["happy", "खुश"], ["sad", "उदास"]],
        travel:      [["airport", "हवाई अड्डा"], ["train", "ट्रेन"], ["hotel", "होटल"], ["taxi", "टैक्सी"], ["ticket", "टिकट"], ["passport", "पासपोर्ट"], ["map", "नक्शा"], ["car", "गाड़ी"], ["bus", "बस"], ["street", "गली"]],
        food:        [["bread", "रोटी"], ["coffee", "कॉफ़ी"], ["milk", "दूध"], ["apple", "सेब"], ["rice", "चावल"], ["meat", "मांस"], ["tea", "चाय"], ["egg", "अंडा"], ["water", "पानी"], ["banana", "केला"]],
        numbers:     [["one", "एक"], ["two", "दो"], ["three", "तीन"], ["four", "चार"], ["five", "पाँच"], ["six", "छह"], ["seven", "सात"], ["eight", "आठ"], ["nine", "नौ"], ["ten", "दस"]],
        colors:      [["red", "लाल"], ["blue", "नीला"], ["green", "हरा"], ["yellow", "पीला"], ["white", "सफ़ेद"], ["black", "काला"], ["purple", "बैंगनी"], ["orange", "नारंगी"], ["pink", "गुलाबी"], ["brown", "भूरा"]],
        people:      [["mother", "माँ"], ["father", "पिता"], ["sister", "बहन"], ["brother", "भाई"], ["son", "बेटा"], ["daughter", "बेटी"], ["teacher", "शिक्षक"], ["doctor", "डॉक्टर"], ["child", "बच्चा"], ["baby", "शिशु"]],
        _phrases: {
            basics: [["hello, how are you?", "नमस्ते, आप कैसे हैं?"], ["goodbye, my friend", "अलविदा, मेरे दोस्त"]],
            greetings: [["good morning, how are you?", "सुप्रभात, आप कैसे हैं?"], ["I love my family", "मैं अपने परिवार से प्यार करता हूँ"]],
            friends: [["the cat drinks water", "बिल्ली पानी पीती है"], ["we are happy", "हम खुश हैं"]],
            travel: [["where is the hotel?", "होटल कहाँ है?"], ["I have one ticket", "मेरे पास एक टिकट है"]],
            food: [["I drink coffee in the morning", "मैं सुबह कॉफ़ी पीता हूँ"], ["the bread and the egg are good", "रोटी और अंडा अच्छे हैं"]],
            numbers: [["I have two cats", "मेरे पास दो बिल्लियाँ हैं"], ["there are three apples", "तीन सेब हैं"]],
            colors: [["the flower is red", "फूल लाल है"], ["the sky is blue", "आकाश नीला है"]],
            people: [["my mother is a doctor", "मेरी माँ डॉक्टर हैं"], ["the teacher is my friend", "शिक्षक मेरे दोस्त हैं"]],
        },
    },
    arabic: {
        basics:      [["hello", "مرحبا"], ["thank you", "شكرا"], ["yes", "نعم"], ["no", "لا"], ["please", "من فضلك"], ["goodbye", "مع السلامة"], ["man", "رجل"], ["woman", "امرأة"], ["boy", "ولد"], ["girl", "بنت"]],
        greetings:   [["good morning", "صباح الخير"], ["good night", "تصبح على خير"], ["good afternoon", "مساء الخير"], ["how are you?", "كيف حالك؟"], ["I'm fine", "أنا بخير"], ["see you later", "أراك لاحقا"], ["friend", "صديق"], ["family", "عائلة"], ["love", "حب"], ["welcome", "أهلا وسهلا"]],
        friends:     [["friend", "صديق"], ["home", "منزل"], ["water", "ماء"], ["food", "طعام"], ["eat", "يأكل"], ["drink", "يشرب"], ["cat", "قطة"], ["dog", "كلب"], ["happy", "سعيد"], ["sad", "حزين"]],
        travel:      [["airport", "مطار"], ["train", "قطار"], ["hotel", "فندق"], ["taxi", "سيارة أجرة"], ["ticket", "تذكرة"], ["passport", "جواز سفر"], ["map", "خريطة"], ["car", "سيارة"], ["bus", "حافلة"], ["street", "شارع"]],
        food:        [["bread", "خبز"], ["coffee", "قهوة"], ["milk", "حليب"], ["apple", "تفاحة"], ["rice", "أرز"], ["meat", "لحم"], ["tea", "شاي"], ["egg", "بيضة"], ["water", "ماء"], ["banana", "موزة"]],
        numbers:     [["one", "واحد"], ["two", "اثنان"], ["three", "ثلاثة"], ["four", "أربعة"], ["five", "خمسة"], ["six", "ستة"], ["seven", "سبعة"], ["eight", "ثمانية"], ["nine", "تسعة"], ["ten", "عشرة"]],
        colors:      [["red", "أحمر"], ["blue", "أزرق"], ["green", "أخضر"], ["yellow", "أصفر"], ["white", "أبيض"], ["black", "أسود"], ["purple", "بنفسجي"], ["orange", "برتقالي"], ["pink", "وردي"], ["brown", "بني"]],
        people:      [["mother", "أم"], ["father", "أب"], ["sister", "أخت"], ["brother", "أخ"], ["son", "ابن"], ["daughter", "ابنة"], ["teacher", "معلم"], ["doctor", "طبيب"], ["child", "طفل"], ["baby", "رضيع"]],
        _phrases: {
            basics: [["hello, how are you?", "مرحبا، كيف حالك؟"], ["goodbye, my friend", "مع السلامة يا صديقي"]],
            greetings: [["good morning, how are you?", "صباح الخير، كيف حالك؟"], ["I love my family", "أحب عائلتي"]],
            friends: [["the cat drinks water", "القطة تشرب الماء"], ["we are happy", "نحن سعداء"]],
            travel: [["where is the hotel?", "أين الفندق؟"], ["I have one ticket", "لدي تذكرة واحدة"]],
            food: [["I drink coffee in the morning", "أشرب القهوة في الصباح"], ["the bread and the egg are good", "الخبز والبيضة جيدان"]],
            numbers: [["I have two cats", "لدي قطتان"], ["there are three apples", "يوجد ثلاث تفاحات"]],
            colors: [["the flower is red", "الزهرة حمراء"], ["the sky is blue", "السماء زرقاء"]],
            people: [["my mother is a doctor", "أمي طبيبة"], ["the teacher is my friend", "المعلم صديقي"]],
        },
    },
    russian: {
        basics:      [["hello", "привет"], ["thank you", "спасибо"], ["yes", "да"], ["no", "нет"], ["please", "пожалуйста"], ["goodbye", "до свидания"], ["man", "мужчина"], ["woman", "женщина"], ["boy", "мальчик"], ["girl", "девочка"]],
        greetings:   [["good morning", "доброе утро"], ["good night", "спокойной ночи"], ["good afternoon", "добрый день"], ["how are you?", "как дела?"], ["I'm fine", "у меня всё хорошо"], ["see you later", "увидимся позже"], ["friend", "друг"], ["family", "семья"], ["love", "любовь"], ["welcome", "добро пожаловать"]],
        friends:     [["friend", "друг"], ["home", "дом"], ["water", "вода"], ["food", "еда"], ["eat", "есть"], ["drink", "пить"], ["cat", "кошка"], ["dog", "собака"], ["happy", "счастливый"], ["sad", "грустный"]],
        travel:      [["airport", "аэропорт"], ["train", "поезд"], ["hotel", "отель"], ["taxi", "такси"], ["ticket", "билет"], ["passport", "паспорт"], ["map", "карта"], ["car", "машина"], ["bus", "автобус"], ["street", "улица"]],
        food:        [["bread", "хлеб"], ["coffee", "кофе"], ["milk", "молоко"], ["apple", "яблоко"], ["rice", "рис"], ["meat", "мясо"], ["tea", "чай"], ["egg", "яйцо"], ["water", "вода"], ["banana", "банан"]],
        numbers:     [["one", "один"], ["two", "два"], ["three", "три"], ["four", "четыре"], ["five", "пять"], ["six", "шесть"], ["seven", "семь"], ["eight", "восемь"], ["nine", "девять"], ["ten", "десять"]],
        colors:      [["red", "красный"], ["blue", "синий"], ["green", "зелёный"], ["yellow", "жёлтый"], ["white", "белый"], ["black", "чёрный"], ["purple", "фиолетовый"], ["orange", "оранжевый"], ["pink", "розовый"], ["brown", "коричневый"]],
        people:      [["mother", "мама"], ["father", "папа"], ["sister", "сестра"], ["brother", "брат"], ["son", "сын"], ["daughter", "дочь"], ["teacher", "учитель"], ["doctor", "врач"], ["child", "ребёнок"], ["baby", "младенец"]],
        _phrases: {
            basics: [["hello, how are you?", "привет, как дела?"], ["goodbye, my friend", "до свидания, мой друг"]],
            greetings: [["good morning, how are you?", "доброе утро, как дела?"], ["I love my family", "я люблю свою семью"]],
            friends: [["the cat drinks water", "кошка пьёт воду"], ["we are happy", "мы счастливы"]],
            travel: [["where is the hotel?", "где отель?"], ["I have one ticket", "у меня один билет"]],
            food: [["I drink coffee in the morning", "я пью кофе утром"], ["the bread and the egg are good", "хлеб и яйцо хорошие"]],
            numbers: [["I have two cats", "у меня две кошки"], ["there are three apples", "здесь три яблока"]],
            colors: [["the flower is red", "цветок красный"], ["the sky is blue", "небо синее"]],
            people: [["my mother is a doctor", "моя мама врач"], ["the teacher is my friend", "учитель мой друг"]],
        },
    },
    turkish: {
        basics:      [["hello", "merhaba"], ["thank you", "teşekkür ederim"], ["yes", "evet"], ["no", "hayır"], ["please", "lütfen"], ["goodbye", "hoşça kal"], ["man", "adam"], ["woman", "kadın"], ["boy", "erkek çocuk"], ["girl", "kız çocuk"]],
        greetings:   [["good morning", "günaydın"], ["good night", "iyi geceler"], ["good afternoon", "iyi günler"], ["how are you?", "nasılsın?"], ["I'm fine", "iyiyim"], ["see you later", "sonra görüşürüz"], ["friend", "arkadaş"], ["family", "aile"], ["love", "aşk"], ["welcome", "hoş geldin"]],
        friends:     [["friend", "arkadaş"], ["home", "ev"], ["water", "su"], ["food", "yiyecek"], ["eat", "yemek"], ["drink", "içmek"], ["cat", "kedi"], ["dog", "köpek"], ["happy", "mutlu"], ["sad", "üzgün"]],
        travel:      [["airport", "havalimanı"], ["train", "tren"], ["hotel", "otel"], ["taxi", "taksi"], ["ticket", "bilet"], ["passport", "pasaport"], ["map", "harita"], ["car", "araba"], ["bus", "otobüs"], ["street", "sokak"]],
        food:        [["bread", "ekmek"], ["coffee", "kahve"], ["milk", "süt"], ["apple", "elma"], ["rice", "pirinç"], ["meat", "et"], ["tea", "çay"], ["egg", "yumurta"], ["water", "su"], ["banana", "muz"]],
        numbers:     [["one", "bir"], ["two", "iki"], ["three", "üç"], ["four", "dört"], ["five", "beş"], ["six", "altı"], ["seven", "yedi"], ["eight", "sekiz"], ["nine", "dokuz"], ["ten", "on"]],
        colors:      [["red", "kırmızı"], ["blue", "mavi"], ["green", "yeşil"], ["yellow", "sarı"], ["white", "beyaz"], ["black", "siyah"], ["purple", "mor"], ["orange", "turuncu"], ["pink", "pembe"], ["brown", "kahverengi"]],
        people:      [["mother", "anne"], ["father", "baba"], ["sister", "kız kardeş"], ["brother", "erkek kardeş"], ["son", "oğul"], ["daughter", "kız"], ["teacher", "öğretmen"], ["doctor", "doktor"], ["child", "çocuk"], ["baby", "bebek"]],
        _phrases: {
            basics: [["hello, how are you?", "merhaba, nasılsın?"], ["goodbye, my friend", "hoşça kal, arkadaşım"]],
            greetings: [["good morning, how are you?", "günaydın, nasılsın?"], ["I love my family", "ailemi seviyorum"]],
            friends: [["the cat drinks water", "kedi su içer"], ["we are happy", "mutluyuz"]],
            travel: [["where is the hotel?", "otel nerede?"], ["I have one ticket", "bir biletim var"]],
            food: [["I drink coffee in the morning", "sabahları kahve içerim"], ["the bread and the egg are good", "ekmek ve yumurta güzel"]],
            numbers: [["I have two cats", "iki kedim var"], ["there are three apples", "üç elma var"]],
            colors: [["the flower is red", "çiçek kırmızı"], ["the sky is blue", "gökyüzü mavi"]],
            people: [["my mother is a doctor", "annem doktordur"], ["the teacher is my friend", "öğretmen arkadaşımdır"]],
        },
    },
    greek: {
        basics:      [["hello", "γεια σου"], ["thank you", "ευχαριστώ"], ["yes", "ναι"], ["no", "όχι"], ["please", "παρακαλώ"], ["goodbye", "αντίο"], ["man", "άνδρας"], ["woman", "γυναίκα"], ["boy", "αγόρι"], ["girl", "κορίτσι"]],
        greetings:   [["good morning", "καλημέρα"], ["good night", "καληνύχτα"], ["good afternoon", "καλησπέρα"], ["how are you?", "τι κάνεις;"], ["I'm fine", "είμαι καλά"], ["see you later", "τα λέμε αργότερα"], ["friend", "φίλος"], ["family", "οικογένεια"], ["love", "αγάπη"], ["welcome", "καλώς ήρθες"]],
        friends:     [["friend", "φίλος"], ["home", "σπίτι"], ["water", "νερό"], ["food", "φαγητό"], ["eat", "τρώω"], ["drink", "πίνω"], ["cat", "γάτα"], ["dog", "σκύλος"], ["happy", "χαρούμενος"], ["sad", "λυπημένος"]],
        travel:      [["airport", "αεροδρόμιο"], ["train", "τρένο"], ["hotel", "ξενοδοχείο"], ["taxi", "ταξί"], ["ticket", "εισιτήριο"], ["passport", "διαβατήριο"], ["map", "χάρτης"], ["car", "αυτοκίνητο"], ["bus", "λεωφορείο"], ["street", "δρόμος"]],
        food:        [["bread", "ψωμί"], ["coffee", "καφές"], ["milk", "γάλα"], ["apple", "μήλο"], ["rice", "ρύζι"], ["meat", "κρέας"], ["tea", "τσάι"], ["egg", "αυγό"], ["water", "νερό"], ["banana", "μπανάνα"]],
        numbers:     [["one", "ένα"], ["two", "δύο"], ["three", "τρία"], ["four", "τέσσερα"], ["five", "πέντε"], ["six", "έξι"], ["seven", "επτά"], ["eight", "οκτώ"], ["nine", "εννέα"], ["ten", "δέκα"]],
        colors:      [["red", "κόκκινο"], ["blue", "μπλε"], ["green", "πράσινο"], ["yellow", "κίτρινο"], ["white", "άσπρο"], ["black", "μαύρο"], ["purple", "μωβ"], ["orange", "πορτοκαλί"], ["pink", "ροζ"], ["brown", "καφέ"]],
        people:      [["mother", "μητέρα"], ["father", "πατέρας"], ["sister", "αδελφή"], ["brother", "αδελφός"], ["son", "γιος"], ["daughter", "κόρη"], ["teacher", "δάσκαλος"], ["doctor", "γιατρός"], ["child", "παιδί"], ["baby", "μωρό"]],
        _phrases: {
            basics: [["hello, how are you?", "γεια σου, τι κάνεις;"], ["goodbye, my friend", "αντίο, φίλε μου"]],
            greetings: [["good morning, how are you?", "καλημέρα, τι κάνεις;"], ["I love my family", "αγαπώ την οικογένειά μου"]],
            friends: [["the cat drinks water", "η γάτα πίνει νερό"], ["we are happy", "είμαστε χαρούμενοι"]],
            travel: [["where is the hotel?", "πού είναι το ξενοδοχείο;"], ["I have one ticket", "έχω ένα εισιτήριο"]],
            food: [["I drink coffee in the morning", "πίνω καφέ το πρωί"], ["the bread and the egg are good", "το ψωμί και το αυγό είναι καλά"]],
            numbers: [["I have two cats", "έχω δύο γάτες"], ["there are three apples", "υπάρχουν τρία μήλα"]],
            colors: [["the flower is red", "το λουλούδι είναι κόκκινο"], ["the sky is blue", "ο ουρανός είναι μπλε"]],
            people: [["my mother is a doctor", "η μητέρα μου είναι γιατρός"], ["the teacher is my friend", "ο δάσκαλος είναι φίλος μου"]],
        },
    },
    hebrew: {
        basics:      [["hello", "שלום"], ["thank you", "תודה"], ["yes", "כן"], ["no", "לא"], ["please", "בבקשה"], ["goodbye", "להתראות"], ["man", "גבר"], ["woman", "אישה"], ["boy", "ילד"], ["girl", "ילדה"]],
        greetings:   [["good morning", "בוקר טוב"], ["good night", "לילה טוב"], ["good afternoon", "צהריים טובים"], ["how are you?", "מה שלומך?"], ["I'm fine", "אני בסדר"], ["see you later", "נתראה אחר כך"], ["friend", "חבר"], ["family", "משפחה"], ["love", "אהבה"], ["welcome", "ברוך הבא"]],
        friends:     [["friend", "חבר"], ["home", "בית"], ["water", "מים"], ["food", "אוכל"], ["eat", "לאכול"], ["drink", "לשתות"], ["cat", "חתול"], ["dog", "כלב"], ["happy", "שמח"], ["sad", "עצוב"]],
        travel:      [["airport", "שדה תעופה"], ["train", "רכבת"], ["hotel", "מלון"], ["taxi", "מונית"], ["ticket", "כרטיס"], ["passport", "דרכון"], ["map", "מפה"], ["car", "מכונית"], ["bus", "אוטובוס"], ["street", "רחוב"]],
        food:        [["bread", "לחם"], ["coffee", "קפה"], ["milk", "חלב"], ["apple", "תפוח"], ["rice", "אורז"], ["meat", "בשר"], ["tea", "תה"], ["egg", "ביצה"], ["water", "מים"], ["banana", "בננה"]],
        numbers:     [["one", "אחת"], ["two", "שתיים"], ["three", "שלוש"], ["four", "ארבע"], ["five", "חמש"], ["six", "שש"], ["seven", "שבע"], ["eight", "שמונה"], ["nine", "תשע"], ["ten", "עשר"]],
        colors:      [["red", "אדום"], ["blue", "כחול"], ["green", "ירוק"], ["yellow", "צהוב"], ["white", "לבן"], ["black", "שחור"], ["purple", "סגול"], ["orange", "כתום"], ["pink", "ורוד"], ["brown", "חום"]],
        people:      [["mother", "אמא"], ["father", "אבא"], ["sister", "אחות"], ["brother", "אח"], ["son", "בן"], ["daughter", "בת"], ["teacher", "מורה"], ["doctor", "רופא"], ["child", "ילד"], ["baby", "תינוק"]],
        _phrases: {
            basics: [["hello, how are you?", "שלום, מה שלומך?"], ["goodbye, my friend", "להתראות, חבר שלי"]],
            greetings: [["good morning, how are you?", "בוקר טוב, מה שלומך?"], ["I love my family", "אני אוהב את המשפחה שלי"]],
            friends: [["the cat drinks water", "החתול שותה מים"], ["we are happy", "אנחנו שמחים"]],
            travel: [["where is the hotel?", "איפה המלון?"], ["I have one ticket", "יש לי כרטיס אחד"]],
            food: [["I drink coffee in the morning", "אני שותה קפה בבוקר"], ["the bread and the egg are good", "הלחם והביצה טובים"]],
            numbers: [["I have two cats", "יש לי שני חתולים"], ["there are three apples", "יש שלושה תפוחים"]],
            colors: [["the flower is red", "הפרח אדום"], ["the sky is blue", "השמיים כחולים"]],
            people: [["my mother is a doctor", "אמא שלי רופאה"], ["the teacher is my friend", "המורה הוא חבר שלי"]],
        },
    },
    polish: {
        basics:      [["hello", "cześć"], ["thank you", "dziękuję"], ["yes", "tak"], ["no", "nie"], ["please", "proszę"], ["goodbye", "do widzenia"], ["man", "mężczyzna"], ["woman", "kobieta"], ["boy", "chłopiec"], ["girl", "dziewczynka"]],
        greetings:   [["good morning", "dzień dobry"], ["good night", "dobranoc"], ["good afternoon", "dzień dobry"], ["how are you?", "jak się masz?"], ["I'm fine", "mam się dobrze"], ["see you later", "do zobaczenia później"], ["friend", "przyjaciel"], ["family", "rodzina"], ["love", "miłość"], ["welcome", "witaj"]],
        friends:     [["friend", "przyjaciel"], ["home", "dom"], ["water", "woda"], ["food", "jedzenie"], ["eat", "jeść"], ["drink", "pić"], ["cat", "kot"], ["dog", "pies"], ["happy", "szczęśliwy"], ["sad", "smutny"]],
        travel:      [["airport", "lotnisko"], ["train", "pociąg"], ["hotel", "hotel"], ["taxi", "taksówka"], ["ticket", "bilet"], ["passport", "paszport"], ["map", "mapa"], ["car", "samochód"], ["bus", "autobus"], ["street", "ulica"]],
        food:        [["bread", "chleb"], ["coffee", "kawa"], ["milk", "mleko"], ["apple", "jabłko"], ["rice", "ryż"], ["meat", "mięso"], ["tea", "herbata"], ["egg", "jajko"], ["water", "woda"], ["banana", "banan"]],
        numbers:     [["one", "jeden"], ["two", "dwa"], ["three", "trzy"], ["four", "cztery"], ["five", "pięć"], ["six", "sześć"], ["seven", "siedem"], ["eight", "osiem"], ["nine", "dziewięć"], ["ten", "dziesięć"]],
        colors:      [["red", "czerwony"], ["blue", "niebieski"], ["green", "zielony"], ["yellow", "żółty"], ["white", "biały"], ["black", "czarny"], ["purple", "fioletowy"], ["orange", "pomarańczowy"], ["pink", "różowy"], ["brown", "brązowy"]],
        people:      [["mother", "matka"], ["father", "ojciec"], ["sister", "siostra"], ["brother", "brat"], ["son", "syn"], ["daughter", "córka"], ["teacher", "nauczyciel"], ["doctor", "lekarz"], ["child", "dziecko"], ["baby", "niemowlę"]],
        _phrases: {
            basics: [["hello, how are you?", "cześć, jak się masz?"], ["goodbye, my friend", "do widzenia, mój przyjacielu"]],
            greetings: [["good morning, how are you?", "dzień dobry, jak się masz?"], ["I love my family", "kocham moją rodzinę"]],
            friends: [["the cat drinks water", "kot pije wodę"], ["we are happy", "jesteśmy szczęśliwi"]],
            travel: [["where is the hotel?", "gdzie jest hotel?"], ["I have one ticket", "mam jeden bilet"]],
            food: [["I drink coffee in the morning", "piję kawę rano"], ["the bread and the egg are good", "chleb i jajko są dobre"]],
            numbers: [["I have two cats", "mam dwa koty"], ["there are three apples", "są trzy jabłka"]],
            colors: [["the flower is red", "kwiat jest czerwony"], ["the sky is blue", "niebo jest niebieskie"]],
            people: [["my mother is a doctor", "moja mama jest lekarką"], ["the teacher is my friend", "nauczyciel jest moim przyjacielem"]],
        },
    },
    indonesian: {
        basics:      [["hello", "halo"], ["thank you", "terima kasih"], ["yes", "ya"], ["no", "tidak"], ["please", "tolong"], ["goodbye", "selamat tinggal"], ["man", "laki-laki"], ["woman", "perempuan"], ["boy", "anak laki-laki"], ["girl", "anak perempuan"]],
        greetings:   [["good morning", "selamat pagi"], ["good night", "selamat malam"], ["good afternoon", "selamat siang"], ["how are you?", "apa kabar?"], ["I'm fine", "saya baik-baik saja"], ["see you later", "sampai nanti"], ["friend", "teman"], ["family", "keluarga"], ["love", "cinta"], ["welcome", "selamat datang"]],
        friends:     [["friend", "teman"], ["home", "rumah"], ["water", "air"], ["food", "makanan"], ["eat", "makan"], ["drink", "minum"], ["cat", "kucing"], ["dog", "anjing"], ["happy", "senang"], ["sad", "sedih"]],
        travel:      [["airport", "bandara"], ["train", "kereta"], ["hotel", "hotel"], ["taxi", "taksi"], ["ticket", "tiket"], ["passport", "paspor"], ["map", "peta"], ["car", "mobil"], ["bus", "bis"], ["street", "jalan"]],
        food:        [["bread", "roti"], ["coffee", "kopi"], ["milk", "susu"], ["apple", "apel"], ["rice", "nasi"], ["meat", "daging"], ["tea", "teh"], ["egg", "telur"], ["water", "air"], ["banana", "pisang"]],
        numbers:     [["one", "satu"], ["two", "dua"], ["three", "tiga"], ["four", "empat"], ["five", "lima"], ["six", "enam"], ["seven", "tujuh"], ["eight", "delapan"], ["nine", "sembilan"], ["ten", "sepuluh"]],
        colors:      [["red", "merah"], ["blue", "biru"], ["green", "hijau"], ["yellow", "kuning"], ["white", "putih"], ["black", "hitam"], ["purple", "ungu"], ["orange", "oranye"], ["pink", "merah muda"], ["brown", "coklat"]],
        people:      [["mother", "ibu"], ["father", "ayah"], ["sister", "kakak perempuan"], ["brother", "kakak laki-laki"], ["son", "anak laki-laki"], ["daughter", "anak perempuan"], ["teacher", "guru"], ["doctor", "dokter"], ["child", "anak"], ["baby", "bayi"]],
        _phrases: {
            basics: [["hello, how are you?", "halo, apa kabar?"], ["goodbye, my friend", "selamat tinggal, temanku"]],
            greetings: [["good morning, how are you?", "selamat pagi, apa kabar?"], ["I love my family", "saya cinta keluarga saya"]],
            friends: [["the cat drinks water", "kucing minum air"], ["we are happy", "kami senang"]],
            travel: [["where is the hotel?", "di mana hotanya?"], ["I have one ticket", "saya punya satu tiket"]],
            food: [["I drink coffee in the morning", "saya minum kopi di pagi hari"], ["the bread and the egg are good", "roti dan telurnya enak"]],
            numbers: [["I have two cats", "saya punya dua kucing"], ["there are three apples", "ada tiga apel"]],
            colors: [["the flower is red", "bunga itu merah"], ["the sky is blue", "langit itu biru"]],
            people: [["my mother is a doctor", "ibu saya dokter"], ["the teacher is my friend", "guru itu teman saya"]],
        },
    },
    vietnamese: {
        basics:      [["hello", "xin chào"], ["thank you", "cảm ơn"], ["yes", "vâng"], ["no", "không"], ["please", "làm ơn"], ["goodbye", "tạm biệt"], ["man", "đàn ông"], ["woman", "phụ nữ"], ["boy", "con trai"], ["girl", "con gái"]],
        greetings:   [["good morning", "chào buổi sáng"], ["good night", "chúc ngủ ngon"], ["good afternoon", "chào buổi chiều"], ["how are you?", "bạn khỏe không?"], ["I'm fine", "tôi khỏe"], ["see you later", "hẹn gặp lại"], ["friend", "bạn"], ["family", "gia đình"], ["love", "tình yêu"], ["welcome", "chào mừng"]],
        friends:     [["friend", "bạn"], ["home", "nhà"], ["water", "nước"], ["food", "đồ ăn"], ["eat", "ăn"], ["drink", "uống"], ["cat", "mèo"], ["dog", "chó"], ["happy", "vui vẻ"], ["sad", "buồn"]],
        travel:      [["airport", "sân bay"], ["train", "tàu hỏa"], ["hotel", "khách sạn"], ["taxi", "taxi"], ["ticket", "vé"], ["passport", "hộ chiếu"], ["map", "bản đồ"], ["car", "ô tô"], ["bus", "xe buýt"], ["street", "đường phố"]],
        food:        [["bread", "bánh mì"], ["coffee", "cà phê"], ["milk", "sữa"], ["apple", "táo"], ["rice", "cơm"], ["meat", "thịt"], ["tea", "trà"], ["egg", "trứng"], ["water", "nước"], ["banana", "chuối"]],
        numbers:     [["one", "một"], ["two", "hai"], ["three", "ba"], ["four", "bốn"], ["five", "năm"], ["six", "sáu"], ["seven", "bảy"], ["eight", "tám"], ["nine", "chín"], ["ten", "mười"]],
        colors:      [["red", "đỏ"], ["blue", "xanh dương"], ["green", "xanh lá"], ["yellow", "vàng"], ["white", "trắng"], ["black", "đen"], ["purple", "tím"], ["orange", "cam"], ["pink", "hồng"], ["brown", "nâu"]],
        people:      [["mother", "mẹ"], ["father", "bố"], ["sister", "chị"], ["brother", "anh"], ["son", "con trai"], ["daughter", "con gái"], ["teacher", "giáo viên"], ["doctor", "bác sĩ"], ["child", "đứa trẻ"], ["baby", "em bé"]],
        _phrases: {
            basics: [["hello, how are you?", "xin chào, bạn khỏe không?"], ["goodbye, my friend", "tạm biệt, bạn của tôi"]],
            greetings: [["good morning, how are you?", "chào buổi sáng, bạn khỏe không?"], ["I love my family", "tôi yêu gia đình mình"]],
            friends: [["the cat drinks water", "con mèo uống nước"], ["we are happy", "chúng tôi vui vẻ"]],
            travel: [["where is the hotel?", "khách sạn ở đâu?"], ["I have one ticket", "tôi có một vé"]],
            food: [["I drink coffee in the morning", "tôi uống cà phê vào buổi sáng"], ["the bread and the egg are good", "bánh mì và trứng đều ngon"]],
            numbers: [["I have two cats", "tôi có hai con mèo"], ["there are three apples", "có ba quả táo"]],
            colors: [["the flower is red", "bông hoa màu đỏ"], ["the sky is blue", "bầu trời màu xanh"]],
            people: [["my mother is a doctor", "mẹ tôi là bác sĩ"], ["the teacher is my friend", "giáo viên là bạn của tôi"]],
        },
    },
    thai: {
        basics:      [["hello", "สวัสดี"], ["thank you", "ขอบคุณ"], ["yes", "ใช่"], ["no", "ไม่"], ["please", "กรุณา"], ["goodbye", "ลาก่อน"], ["man", "ผู้ชาย"], ["woman", "ผู้หญิง"], ["boy", "เด็กผู้ชาย"], ["girl", "เด็กผู้หญิง"]],
        greetings:   [["good morning", "สวัสดีตอนเช้า"], ["good night", "ราตรีสวัสดิ์"], ["good afternoon", "สวัสดีตอนบ่าย"], ["how are you?", "สบายดีไหม?"], ["I'm fine", "สบายดี"], ["see you later", "แล้วเจอกัน"], ["friend", "เพื่อน"], ["family", "ครอบครัว"], ["love", "ความรัก"], ["welcome", "ยินดีต้อนรับ"]],
        friends:     [["friend", "เพื่อน"], ["home", "บ้าน"], ["water", "น้ำ"], ["food", "อาหาร"], ["eat", "กิน"], ["drink", "ดื่ม"], ["cat", "แมว"], ["dog", "หมา"], ["happy", "มีความสุข"], ["sad", "เสียใจ"]],
        travel:      [["airport", "สนามบิน"], ["train", "รถไฟ"], ["hotel", "โรงแรม"], ["taxi", "แท็กซี่"], ["ticket", "ตั๋ว"], ["passport", "หนังสือเดินทาง"], ["map", "แผนที่"], ["car", "รถยนต์"], ["bus", "รถบัส"], ["street", "ถนน"]],
        food:        [["bread", "ขนมปัง"], ["coffee", "กาแฟ"], ["milk", "นม"], ["apple", "แอปเปิ้ล"], ["rice", "ข้าว"], ["meat", "เนื้อ"], ["tea", "ชา"], ["egg", "ไข่"], ["water", "น้ำ"], ["banana", "กล้วย"]],
        numbers:     [["one", "หนึ่ง"], ["two", "สอง"], ["three", "สาม"], ["four", "สี่"], ["five", "ห้า"], ["six", "หก"], ["seven", "เจ็ด"], ["eight", "แปด"], ["nine", "เก้า"], ["ten", "สิบ"]],
        colors:      [["red", "แดง"], ["blue", "น้ำเงิน"], ["green", "เขียว"], ["yellow", "เหลือง"], ["white", "ขาว"], ["black", "ดำ"], ["purple", "ม่วง"], ["orange", "ส้ม"], ["pink", "ชมพู"], ["brown", "น้ำตาล"]],
        people:      [["mother", "แม่"], ["father", "พ่อ"], ["sister", "พี่สาว"], ["brother", "พี่ชาย"], ["son", "ลูกชาย"], ["daughter", "ลูกสาว"], ["teacher", "ครู"], ["doctor", "หมอ"], ["child", "เด็ก"], ["baby", "ทารก"]],
        _phrases: {
            basics: [["hello, how are you?", "สวัสดี สบายดีไหม?"], ["goodbye, my friend", "ลาก่อน เพื่อนรัก"]],
            greetings: [["good morning, how are you?", "สวัสดีตอนเช้า สบายดีไหม?"], ["I love my family", "ฉันรักครอบครัว"]],
            friends: [["the cat drinks water", "แมวดื่มน้ำ"], ["we are happy", "เรามีความสุข"]],
            travel: [["where is the hotel?", "โรงแรมอยู่ไหน?"], ["I have one ticket", "ฉันมีตั๋วหนึ่งใบ"]],
            food: [["I drink coffee in the morning", "ฉันดื่มกาแฟตอนเช้า"], ["the bread and the egg are good", "ขนมปังและไข่อร่อย"]],
            numbers: [["I have two cats", "ฉันมีแมวสองตัว"], ["there are three apples", "มีแอปเปิ้ลสามลูก"]],
            colors: [["the flower is red", "ดอกไม้สีแดง"], ["the sky is blue", "ท้องฟ้าสีน้ำเงิน"]],
            people: [["my mother is a doctor", "แม่ของฉันเป็นหมอ"], ["the teacher is my friend", "ครูเป็นเพื่อนของฉัน"]],
        },
    },
    ukrainian: {
        basics:      [["hello", "привіт"], ["thank you", "дякую"], ["yes", "так"], ["no", "ні"], ["please", "будь ласка"], ["goodbye", "до побачення"], ["man", "чоловік"], ["woman", "жінка"], ["boy", "хлопчик"], ["girl", "дівчинка"]],
        greetings:   [["good morning", "доброго ранку"], ["good night", "на добраніч"], ["good afternoon", "добрий день"], ["how are you?", "як справи?"], ["I'm fine", "у мене все добре"], ["see you later", "побачимося пізніше"], ["friend", "друг"], ["family", "родина"], ["love", "кохання"], ["welcome", "ласкаво просимо"]],
        friends:     [["friend", "друг"], ["home", "дім"], ["water", "вода"], ["food", "їжа"], ["eat", "їсти"], ["drink", "пити"], ["cat", "кіт"], ["dog", "собака"], ["happy", "щасливий"], ["sad", "сумний"]],
        travel:      [["airport", "аеропорт"], ["train", "поїзд"], ["hotel", "готель"], ["taxi", "таксі"], ["ticket", "квиток"], ["passport", "паспорт"], ["map", "карта"], ["car", "машина"], ["bus", "автобус"], ["street", "вулиця"]],
        food:        [["bread", "хліб"], ["coffee", "кава"], ["milk", "молоко"], ["apple", "яблуко"], ["rice", "рис"], ["meat", "м'ясо"], ["tea", "чай"], ["egg", "яйце"], ["water", "вода"], ["banana", "банан"]],
        numbers:     [["one", "один"], ["two", "два"], ["three", "три"], ["four", "чотири"], ["five", "п'ять"], ["six", "шість"], ["seven", "сім"], ["eight", "вісім"], ["nine", "дев'ять"], ["ten", "десять"]],
        colors:      [["red", "червоний"], ["blue", "синій"], ["green", "зелений"], ["yellow", "жовтий"], ["white", "білий"], ["black", "чорний"], ["purple", "фіолетовий"], ["orange", "помаранчевий"], ["pink", "рожевий"], ["brown", "коричневий"]],
        people:      [["mother", "мати"], ["father", "батько"], ["sister", "сестра"], ["brother", "брат"], ["son", "син"], ["daughter", "донька"], ["teacher", "вчитель"], ["doctor", "лікар"], ["child", "дитина"], ["baby", "немовля"]],
        _phrases: {
            basics: [["hello, how are you?", "привіт, як справи?"], ["goodbye, my friend", "до побачення, мій друже"]],
            greetings: [["good morning, how are you?", "доброго ранку, як справи?"], ["I love my family", "я люблю свою родину"]],
            friends: [["the cat drinks water", "кіт п'є воду"], ["we are happy", "ми щасливі"]],
            travel: [["where is the hotel?", "де готель?"], ["I have one ticket", "у мене один квиток"]],
            food: [["I drink coffee in the morning", "я п'ю каву вранці"], ["the bread and the egg are good", "хліб і яйце хороші"]],
            numbers: [["I have two cats", "у мене два коти"], ["there are three apples", "є три яблука"]],
            colors: [["the flower is red", "квітка червона"], ["the sky is blue", "небо синє"]],
            people: [["my mother is a doctor", "моя мати лікарка"], ["the teacher is my friend", "вчитель мій друг"]],
        },
    },
    swahili: {
        basics:      [["hello", "habari"], ["thank you", "asante"], ["yes", "ndiyo"], ["no", "hapana"], ["please", "tafadhali"], ["goodbye", "kwaheri"], ["man", "mwanamume"], ["woman", "mwanamke"], ["boy", "mvulana"], ["girl", "msichana"]],
        greetings:   [["good morning", "habari za asubuhi"], ["good night", "usiku mwema"], ["good afternoon", "habari za mchana"], ["how are you?", "habari gani?"], ["I'm fine", "niko salama"], ["see you later", "tutaonana baadaye"], ["friend", "rafiki"], ["family", "familia"], ["love", "upendo"], ["welcome", "karibu"]],
        friends:     [["friend", "rafiki"], ["home", "nyumbani"], ["water", "maji"], ["food", "chakula"], ["eat", "kula"], ["drink", "kunywa"], ["cat", "paka"], ["dog", "mbwa"], ["happy", "furaha"], ["sad", "huzuni"]],
        travel:      [["airport", "uwanja wa ndege"], ["train", "garimoshi"], ["hotel", "hoteli"], ["taxi", "teksi"], ["ticket", "tiketi"], ["passport", "pasipoti"], ["map", "ramani"], ["car", "gari"], ["bus", "basi"], ["street", "barabara"]],
        food:        [["bread", "mkate"], ["coffee", "kahawa"], ["milk", "maziwa"], ["apple", "tofaa"], ["rice", "wali"], ["meat", "nyama"], ["tea", "chai"], ["egg", "yai"], ["water", "maji"], ["banana", "ndizi"]],
        numbers:     [["one", "moja"], ["two", "mbili"], ["three", "tatu"], ["four", "nne"], ["five", "tano"], ["six", "sita"], ["seven", "saba"], ["eight", "nane"], ["nine", "tisa"], ["ten", "kumi"]],
        colors:      [["red", "nyekundu"], ["blue", "bluu"], ["green", "kijani"], ["yellow", "manjano"], ["white", "nyeupe"], ["black", "nyeusi"], ["purple", "zambarau"], ["orange", "chungwa"], ["pink", "waridi"], ["brown", "kahawia"]],
        people:      [["mother", "mama"], ["father", "baba"], ["sister", "dada"], ["brother", "kaka"], ["son", "mwana"], ["daughter", "binti"], ["teacher", "mwalimu"], ["doctor", "daktari"], ["child", "mtoto"], ["baby", "mtoto mchanga"]],
        _phrases: {
            basics: [["hello, how are you?", "habari, habari gani?"], ["goodbye, my friend", "kwaheri, rafiki yangu"]],
            greetings: [["good morning, how are you?", "habari za asubuhi, habari gani?"], ["I love my family", "nawapenda familia yangu"]],
            friends: [["the cat drinks water", "paka anakunywa maji"], ["we are happy", "tunafurahi"]],
            travel: [["where is the hotel?", "hoteli iko wapi?"], ["I have one ticket", "nina tiketi moja"]],
            food: [["I drink coffee in the morning", "nakunywa kahawa asubuhi"], ["the bread and the egg are good", "mkate na yai ni vizuri"]],
            numbers: [["I have two cats", "nina paka wawili"], ["there are three apples", "kuna matofaa matatu"]],
            colors: [["the flower is red", "ua ni nyekundu"], ["the sky is blue", "anga ni bluu"]],
            people: [["my mother is a doctor", "mama yangu ni daktari"], ["the teacher is my friend", "mwalimu ni rafiki yangu"]],
        },
    },
};

// Build full course objects from the shared lesson blueprint + translations.
function buildCourses() {
    const courses = {};
    for (const [langId, t] of Object.entries(TRANSLATIONS)) {
        const units = [];
        const unitMap = [
            { id: "u1", title: "Rookie", color: "#58cc02", lessons: ["basics", "greetings", "friends"] },
            { id: "u2", title: "Explorer", color: "#1cb0f6", lessons: ["travel", "food", "numbers"] },
            { id: "u3", title: "Adventurer", color: "#ffc800", lessons: ["colors", "people"] },
        ];

        for (const u of unitMap) {
            const lessons = u.lessons.map((lid) => {
                const blueprint = BASIC_LESSON[lid];
                const vocab = blueprint.vocab.map(([e, , emoji]) => {
                    const found = (t[lid] || []).find(([en]) => en === e);
                    return { e, t: found ? found[1] : e, emoji };
                });
                const phrases = (t._phrases[lid] || []).map(([e, target]) => ({ e, t: target }));
                return {
                    id: `${langId}-${lid}`,
                    title: blueprint.title,
                    type: "lesson",
                    xp: 10,
                    vocab,
                    phrases,
                };
            });
            units.push({ id: `${langId}-${u.id}`, title: u.title, color: u.color, lessons });
        }
        courses[langId] = { units };
    }
    return courses;
}

const COURSES = buildCourses();

module.exports = { LANGUAGE_CATALOG, COURSES };