// ─────────────────────────────────────────────────────────────
// Simplified Chinese (Mandarin) translations for the shared deep
// English syllabus (learnDeepEnglish.js). One lesson per id.
//   vocab:   [english, target, gloss]   gloss = Mandarin pinyin
//   phrases: [english, target, gloss]   gloss = full-sentence pinyin
// ─────────────────────────────────────────────────────────────

module.exports = {
  d11: {
    vocab: [
      ["eleven", "十一", "shí yī"],
      ["twelve", "十二", "shí èr"],
      ["thirteen", "十三", "shí sān"],
      ["fourteen", "十四", "shí sì"],
      ["fifteen", "十五", "shí wǔ"],
      ["sixteen", "十六", "shí liù"],
      ["seventeen", "十七", "shí qī"],
      ["eighteen", "十八", "shí bā"],
      ["nineteen", "十九", "shí jiǔ"],
      ["twenty", "二十", "èr shí"],
    ],
    phrases: [
      ["I have fifteen apples", "我有十五个苹果", "wǒ yǒu shíwǔ gè píngguǒ"],
      ["There are twenty people", "有二十个人", "yǒu èrshí gè rén"],
    ],
  },
  d21: {
    vocab: [
      ["thirty", "三十", "sān shí"],
      ["forty", "四十", "sì shí"],
      ["fifty", "五十", "wǔ shí"],
      ["sixty", "六十", "liù shí"],
      ["seventy", "七十", "qī shí"],
      ["eighty", "八十", "bā shí"],
      ["ninety", "九十", "jiǔ shí"],
      ["hundred", "百", "bǎi"],
      ["number", "数字", "shù zì"],
      ["zero", "零", "líng"],
    ],
    phrases: [
      ["There are fifty students", "有五十个学生", "yǒu wǔshí gè xuéshēng"],
      ["One hundred days", "一百天", "yìbǎi tiān"],
    ],
  },
  d22: {
    vocab: [
      ["morning", "早上", "zǎo shang"],
      ["afternoon", "下午", "xià wǔ"],
      ["evening", "晚上", "wǎn shang"],
      ["night", "夜晚", "yè wǎn"],
      ["hour", "小时", "xiǎo shí"],
      ["minute", "分钟", "fēn zhōng"],
      ["now", "现在", "xiàn zài"],
      ["later", "以后", "yǐ hòu"],
    ],
    phrases: [
      ["I wake up in the morning", "我早上醒来", "wǒ zǎoshang xǐnglái"],
      ["See you later tonight", "今晚晚点见", "jīnwǎn wǎndiǎn jiàn"],
    ],
  },
  d23: {
    vocab: [
      ["monday", "星期一", "xīngqī yī"],
      ["tuesday", "星期二", "xīngqī èr"],
      ["wednesday", "星期三", "xīngqī sān"],
      ["thursday", "星期四", "xīngqī sì"],
      ["friday", "星期五", "xīngqī wǔ"],
      ["saturday", "星期六", "xīngqī liù"],
      ["sunday", "星期日", "xīngqī rì"],
      ["today", "今天", "jīn tiān"],
      ["tomorrow", "明天", "míng tiān"],
      ["yesterday", "昨天", "zuó tiān"],
    ],
    phrases: [
      ["Today is Monday", "今天是星期一", "jīntiān shì xīngqī yī"],
      ["I work on Friday", "我星期五上班", "wǒ xīngqī wǔ shàngbān"],
    ],
  },
  d24: {
    vocab: [
      ["january", "一月", "yī yuè"],
      ["february", "二月", "èr yuè"],
      ["march", "三月", "sān yuè"],
      ["april", "四月", "sì yuè"],
      ["may", "五月", "wǔ yuè"],
      ["june", "六月", "liù yuè"],
      ["july", "七月", "qī yuè"],
      ["august", "八月", "bā yuè"],
      ["september", "九月", "jiǔ yuè"],
      ["october", "十月", "shí yuè"],
    ],
    phrases: [
      ["My birthday is in May", "我的生日在五月", "wǒ de shēngrì zài wǔ yuè"],
      ["January is cold", "一月很冷", "yī yuè hěn lěng"],
    ],
  },
  d31: {
    vocab: [
      ["water", "水", "shuǐ"],
      ["coffee", "咖啡", "kā fēi"],
      ["tea", "茶", "chá"],
      ["milk", "牛奶", "niú nǎi"],
      ["juice", "果汁", "guǒ zhī"],
      ["wine", "葡萄酒", "pú táo jiǔ"],
      ["beer", "啤酒", "pí jiǔ"],
      ["soda", "汽水", "qì shuǐ"],
    ],
    phrases: [
      ["I drink water every day", "我每天都喝水", "wǒ měitiān dōu hē shuǐ"],
      ["Do you want some tea?", "你想喝点茶吗？", "nǐ xiǎng hē diǎn chá ma?"],
    ],
  },
  d32: {
    vocab: [
      ["breakfast", "早餐", "zǎo cān"],
      ["lunch", "午餐", "wǔ cān"],
      ["dinner", "晚餐", "wǎn cān"],
      ["hungry", "饿", "è"],
      ["thirsty", "渴", "kě"],
      ["taste", "味道", "wèi dào"],
      ["delicious", "好吃", "hǎo chī"],
      ["full", "饱", "bǎo"],
    ],
    phrases: [
      ["Breakfast is ready", "早餐准备好了", "zǎocān zhǔnbèi hǎo le"],
      ["I am very hungry", "我很饿", "wǒ hěn è"],
    ],
  },
  d33: {
    vocab: [
      ["apple", "苹果", "píng guǒ"],
      ["banana", "香蕉", "xiāng jiāo"],
      ["orange", "橙子", "chéng zi"],
      ["grape", "葡萄", "pú táo"],
      ["strawberry", "草莓", "cǎo méi"],
      ["watermelon", "西瓜", "xī guā"],
      ["peach", "桃子", "táo zi"],
      ["lemon", "柠檬", "níng méng"],
    ],
    phrases: [
      ["The watermelon is sweet", "西瓜很甜", "xīguā hěn tián"],
      ["I love strawberries", "我爱吃草莓", "wǒ ài chī cǎoméi"],
    ],
  },
  d41: {
    vocab: [
      ["tomato", "西红柿", "xī hóng shì"],
      ["potato", "土豆", "tǔ dòu"],
      ["carrot", "胡萝卜", "hú luó bo"],
      ["onion", "洋葱", "yáng cōng"],
      ["corn", "玉米", "yù mǐ"],
      ["salt", "盐", "yán"],
      ["sugar", "糖", "táng"],
      ["oil", "油", "yóu"],
    ],
    phrases: [
      ["The salad has tomatoes", "沙拉里有西红柿", "shālā lǐ yǒu xīhóngshì"],
      ["I don't like onions", "我不喜欢洋葱", "wǒ bù xǐhuān yángcōng"],
    ],
  },
  d42: {
    vocab: [
      ["menu", "菜单", "cài dān"],
      ["waiter", "服务员", "fú wù yuán"],
      ["order", "点菜", "diǎn cài"],
      ["table", "桌子", "zhuō zi"],
      ["bill", "账单", "zhàng dān"],
      ["spoon", "勺子", "sháo zi"],
      ["fork", "叉子", "chā zi"],
      ["knife", "刀", "dāo"],
    ],
    phrases: [
      ["Can I see the menu?", "我能看看菜单吗？", "wǒ néng kànkan càidān ma?"],
      ["The bill, please", "请给我账单", "qǐng gěi wǒ zhàngdān"],
    ],
  },
  d43: {
    vocab: [
      ["good", "好", "hǎo"],
      ["bad", "坏", "huài"],
      ["big", "大", "dà"],
      ["small", "小", "xiǎo"],
      ["hot", "热", "rè"],
      ["cold", "冷", "lěng"],
      ["new", "新", "xīn"],
      ["old", "旧", "jiù"],
    ],
    phrases: [
      ["The soup is hot", "汤很热", "tāng hěn rè"],
      ["This is a small car", "这是一辆小车", "zhè shì yí liàng xiǎo chē"],
    ],
  },
  d51: {
    vocab: [
      ["grandfather", "爷爷", "yé ye"],
      ["grandmother", "奶奶", "nǎi nai"],
      ["uncle", "叔叔", "shū shu"],
      ["aunt", "阿姨", "ā yí"],
      ["cousin", "表亲", "biǎo qīn"],
      ["husband", "丈夫", "zhàng fu"],
      ["wife", "妻子", "qī zi"],
      ["baby", "婴儿", "yīng ér"],
    ],
    phrases: [
      ["My grandmother is kind", "我奶奶很善良", "wǒ nǎinai hěn shànliáng"],
      ["My uncle has a farm", "我叔叔有一个农场", "wǒ shūshu yǒu yí gè nóngchǎng"],
    ],
  },
  d52: {
    vocab: [
      ["head", "头", "tóu"],
      ["eye", "眼睛", "yǎn jing"],
      ["ear", "耳朵", "ěr duo"],
      ["nose", "鼻子", "bí zi"],
      ["mouth", "嘴", "zuǐ"],
      ["hand", "手", "shǒu"],
      ["leg", "腿", "tuǐ"],
      ["foot", "脚", "jiǎo"],
    ],
    phrases: [
      ["Close your eyes", "闭上你的眼睛", "bìshàng nǐ de yǎnjing"],
      ["I wash my hands", "我洗手", "wǒ xǐ shǒu"],
    ],
  },
  d53: {
    vocab: [
      ["happy", "开心", "kāi xīn"],
      ["sad", "伤心", "shāng xīn"],
      ["angry", "生气", "shēng qì"],
      ["tired", "累", "lèi"],
      ["scared", "害怕", "hài pà"],
      ["excited", "兴奋", "xīng fèn"],
      ["calm", "平静", "píng jìng"],
      ["proud", "自豪", "zì háo"],
    ],
    phrases: [
      ["I feel very tired", "我觉得很累", "wǒ juéde hěn lèi"],
      ["She looks happy today", "她今天看起来很开心", "tā jīntiān kànqǐlái hěn kāixīn"],
    ],
  },
  d61: {
    vocab: [
      ["sun", "太阳", "tài yáng"],
      ["rain", "雨", "yǔ"],
      ["snow", "雪", "xuě"],
      ["wind", "风", "fēng"],
      ["cloudy", "多云", "duō yún"],
      ["storm", "暴风雨", "bào fēng yǔ"],
      ["warm", "暖和", "nuǎn huo"],
      ["cool", "凉爽", "liáng shuǎng"],
    ],
    phrases: [
      ["It is raining today", "今天下雨", "jīntiān xià yǔ"],
      ["The sun is shining", "太阳在照耀", "tàiyáng zài zhàoyào"],
    ],
  },
  d62: {
    vocab: [
      ["spring", "春天", "chūn tiān"],
      ["summer", "夏天", "xià tiān"],
      ["autumn", "秋天", "qiū tiān"],
      ["winter", "冬天", "dōng tiān"],
      ["season", "季节", "jì jié"],
      ["weather", "天气", "tiān qì"],
      ["month", "月", "yuè"],
      ["year", "年", "nián"],
    ],
    phrases: [
      ["Winter is very cold", "冬天很冷", "dōngtiān hěn lěng"],
      ["Summer is my favorite season", "夏天是我最喜欢的季节", "xiàtiān shì wǒ zuì xǐhuān de jìjié"],
    ],
  },
  d63: {
    vocab: [
      ["shirt", "衬衫", "chèn shān"],
      ["pants", "裤子", "kù zi"],
      ["shoes", "鞋", "xié"],
      ["dress", "连衣裙", "lián yī qún"],
      ["hat", "帽子", "mào zi"],
      ["coat", "外套", "wài tào"],
      ["socks", "袜子", "wà zi"],
      ["jacket", "夹克", "jiá kè"],
    ],
    phrases: [
      ["I buy a new shirt", "我买了一件新衬衫", "wǒ mǎi le yí jiàn xīn chènshān"],
      ["My shoes are black", "我的鞋是黑色的", "wǒ de xié shì hēisè de"],
    ],
  },
  d71: {
    vocab: [
      ["house", "房子", "fáng zi"],
      ["kitchen", "厨房", "chú fáng"],
      ["bedroom", "卧室", "wò shì"],
      ["bathroom", "浴室", "yù shì"],
      ["garden", "花园", "huā yuán"],
      ["door", "门", "mén"],
      ["window", "窗户", "chuāng hu"],
      ["street", "街道", "jiē dào"],
    ],
    phrases: [
      ["The house has a big garden", "房子有一个大花园", "fángzi yǒu yí gè dà huāyuán"],
      ["Close the door, please", "请关门", "qǐng guānmén"],
    ],
  },
  d72: {
    vocab: [
      ["table", "桌子", "zhuō zi"],
      ["chair", "椅子", "yǐ zi"],
      ["bed", "床", "chuáng"],
      ["sofa", "沙发", "shā fā"],
      ["lamp", "灯", "dēng"],
      ["mirror", "镜子", "jìng zi"],
      ["clock", "时钟", "shí zhōng"],
      ["carpet", "地毯", "dì tǎn"],
    ],
    phrases: [
      ["The clock is on the wall", "时钟在墙上", "shízhōng zài qiáng shàng"],
      ["I sit on the sofa", "我坐在沙发上", "wǒ zuò zài shāfā shàng"],
    ],
  },
  d73: {
    vocab: [
      ["city", "城市", "chéng shì"],
      ["park", "公园", "gōng yuán"],
      ["market", "市场", "shì chǎng"],
      ["bridge", "桥", "qiáo"],
      ["building", "大楼", "dà lóu"],
      ["square", "广场", "guǎng chǎng"],
      ["library", "图书馆", "tú shū guǎn"],
      ["station", "车站", "chē zhàn"],
    ],
    phrases: [
      ["The library is in the city", "图书馆在城市里", "túshūguǎn zài chéngshì lǐ"],
      ["We meet in the park", "我们在公园见面", "wǒmen zài gōngyuán jiànmiàn"],
    ],
  },
  d81: {
    vocab: [
      ["bus", "公共汽车", "gōng gòng qì chē"],
      ["car", "汽车", "qì chē"],
      ["train", "火车", "huǒ chē"],
      ["plane", "飞机", "fēi jī"],
      ["boat", "船", "chuán"],
      ["bike", "自行车", "zì xíng chē"],
      ["subway", "地铁", "dì tiě"],
      ["flight", "航班", "háng bān"],
    ],
    phrases: [
      ["I go to work by bus", "我坐公共汽车上班", "wǒ zuò gōnggòngqìchē shàngbān"],
      ["The plane is late", "飞机晚点了", "fēijī wǎndiǎn le"],
    ],
  },
  d82: {
    vocab: [
      ["left", "左", "zuǒ"],
      ["right", "右", "yòu"],
      ["straight", "直走", "zhí zǒu"],
      ["near", "近", "jìn"],
      ["far", "远", "yuǎn"],
      ["north", "北", "běi"],
      ["here", "这里", "zhè lǐ"],
      ["there", "那里", "nà lǐ"],
    ],
    phrases: [
      ["Turn left at the park", "在公园那里左转", "zài gōngyuán nàlǐ zuǒzhuǎn"],
      ["The station is near here", "车站离这里很近", "chēzhàn lí zhèlǐ hěn jìn"],
    ],
  },
  d83: {
    vocab: [
      ["hotel", "酒店", "jiǔ diàn"],
      ["room", "房间", "fáng jiān"],
      ["key", "钥匙", "yào shi"],
      ["reservation", "预订", "yù dìng"],
      ["guest", "客人", "kè rén"],
      ["check-in", "入住", "rù zhù"],
      ["luggage", "行李", "xíng li"],
      ["trip", "旅行", "lǚ xíng"],
    ],
    phrases: [
      ["I have a reservation", "我有预订", "wǒ yǒu yùdìng"],
      ["Welcome to the hotel", "欢迎来到酒店", "huānyíng láidào jiǔdiàn"],
    ],
  },
  d91: {
    vocab: [
      ["work", "工作", "gōng zuò"],
      ["office", "办公室", "bàn gōng shì"],
      ["job", "职业", "zhí yè"],
      ["boss", "老板", "lǎo bǎn"],
      ["colleague", "同事", "tóng shì"],
      ["meeting", "会议", "huì yì"],
      ["salary", "工资", "gōng zī"],
      ["manager", "经理", "jīng lǐ"],
    ],
    phrases: [
      ["The meeting is at nine", "会议在九点", "huìyì zài jiǔ diǎn"],
      ["She is my colleague", "她是我的同事", "tā shì wǒ de tóngshì"],
    ],
  },
  d92: {
    vocab: [
      ["school", "学校", "xué xiào"],
      ["study", "学习", "xué xí"],
      ["homework", "作业", "zuò yè"],
      ["exam", "考试", "kǎo shì"],
      ["class", "课", "kè"],
      ["library", "图书馆", "tú shū guǎn"],
      ["lesson", "课程", "kè chéng"],
      ["question", "问题", "wèn tí"],
    ],
    phrases: [
      ["I study every evening", "我每天晚上学习", "wǒ měitiān wǎnshang xuéxí"],
      ["The exam is next week", "考试在下周", "kǎoshì zài xiàzhōu"],
    ],
  },
  d93: {
    vocab: [
      ["health", "健康", "jiàn kāng"],
      ["sick", "生病", "shēng bìng"],
      ["pain", "疼痛", "téng tòng"],
      ["medicine", "药", "yào"],
      ["hospital", "医院", "yī yuàn"],
      ["healthy", "健康的", "jiàn kāng de"],
      ["rest", "休息", "xiū xi"],
      ["doctor", "医生", "yī shēng"],
    ],
    phrases: [
      ["I feel sick today", "我今天感觉不舒服", "wǒ jīntiān gǎnjué bù shūfu"],
      ["Get some rest", "好好休息", "hǎohǎo xiūxi"],
    ],
  },
  d101: {
    vocab: [
      ["soccer", "足球", "zú qiú"],
      ["basketball", "篮球", "lán qiú"],
      ["tennis", "网球", "wǎng qiú"],
      ["swim", "游泳", "yóu yǒng"],
      ["run", "跑步", "pǎo bù"],
      ["team", "队伍", "duì wǔ"],
      ["game", "比赛", "bǐ sài"],
      ["win", "赢", "yíng"],
    ],
    phrases: [
      ["We play soccer on Sunday", "我们星期日踢足球", "wǒmen xīngqī rì tī zúqiú"],
      ["Our team won the game", "我们队赢了比赛", "wǒmen duì yíng le bǐsài"],
    ],
  },
  d102: {
    vocab: [
      ["read", "阅读", "yuè dú"],
      ["music", "音乐", "yīn yuè"],
      ["sing", "唱歌", "chàng gē"],
      ["dance", "跳舞", "tiào wǔ"],
      ["draw", "画画", "huà huà"],
      ["cook", "做饭", "zuò fàn"],
      ["travel", "旅行", "lǚ xíng"],
      ["photo", "照片", "zhào piàn"],
    ],
    phrases: [
      ["I love to read books", "我喜欢读书", "wǒ xǐhuān dúshū"],
      ["She sings very well", "她唱得很好", "tā chàng de hěn hǎo"],
    ],
  },
  d103: {
    vocab: [
      ["tree", "树", "shù"],
      ["mountain", "山", "shān"],
      ["river", "河", "hé"],
      ["sea", "海", "hǎi"],
      ["forest", "森林", "sēn lín"],
      ["flower", "花", "huā"],
      ["sky", "天空", "tiān kōng"],
      ["land", "陆地", "lù dì"],
    ],
    phrases: [
      ["The river is very long", "这条河很长", "zhè tiáo hé hěn cháng"],
      ["Look at the mountains", "看看那些山", "kànkan nàxiē shān"],
    ],
  },
  d111: {
    vocab: [
      ["horse", "马", "mǎ"],
      ["cow", "牛", "niú"],
      ["bird", "鸟", "niǎo"],
      ["fish", "鱼", "yú"],
      ["rabbit", "兔子", "tù zi"],
      ["tiger", "老虎", "lǎo hǔ"],
      ["elephant", "大象", "dà xiàng"],
      ["monkey", "猴子", "hóu zi"],
    ],
    phrases: [
      ["The bird sings in the morning", "鸟儿在早上唱歌", "niǎor zài zǎoshang chànggē"],
      ["The elephant is big", "大象很大", "dàxiàng hěn dà"],
    ],
  },
  d112: {
    vocab: [
      ["china", "中国", "Zhōng guó"],
      ["india", "印度", "Yìn dù"],
      ["japan", "日本", "Rì běn"],
      ["france", "法国", "Fǎ guó"],
      ["brazil", "巴西", "Bā xī"],
      ["germany", "德国", "Dé guó"],
      ["america", "美国", "Měi guó"],
      ["pakistan", "巴基斯坦", "Bā jī sī tǎn"],
    ],
    phrases: [
      ["I want to visit Japan", "我想去日本旅游", "wǒ xiǎng qù Rìběn lǚyóu"],
      ["She is from Brazil", "她来自巴西", "tā láizì Bāxī"],
    ],
  },
  d113: {
    vocab: [
      ["english", "英语", "Yīng yǔ"],
      ["chinese", "汉语", "Hàn yǔ"],
      ["spanish", "西班牙语", "Xī bān yá yǔ"],
      ["arabic", "阿拉伯语", "Ā lā bó yǔ"],
      ["hindi", "印地语", "Yìn dì yǔ"],
      ["french", "法语", "Fǎ yǔ"],
      ["japanese", "日语", "Rì yǔ"],
      ["korean", "韩语", "Hán yǔ"],
    ],
    phrases: [
      ["Do you speak English?", "你会说英语吗？", "nǐ huì shuō Yīngyǔ ma?"],
      ["I am learning Chinese", "我在学汉语", "wǒ zài xué Hànyǔ"],
    ],
  },
  d121: {
    vocab: [
      ["go", "去", "qù"],
      ["come", "来", "lái"],
      ["see", "看见", "kàn jiàn"],
      ["want", "想要", "xiǎng yào"],
      ["need", "需要", "xū yào"],
      ["like", "喜欢", "xǐ huān"],
      ["can", "能", "néng"],
      ["have", "有", "yǒu"],
    ],
    phrases: [
      ["I want to go home", "我想回家", "wǒ xiǎng huíjiā"],
      ["Can you come here?", "你能来这里吗？", "nǐ néng lái zhèlǐ ma?"],
    ],
  },
  d122: {
    vocab: [
      ["know", "知道", "zhī dào"],
      ["think", "想", "xiǎng"],
      ["say", "说", "shuō"],
      ["give", "给", "gěi"],
      ["take", "拿", "ná"],
      ["make", "做", "zuò"],
      ["find", "找到", "zhǎo dào"],
      ["help", "帮助", "bāng zhù"],
    ],
    phrases: [
      ["I know the answer", "我知道答案", "wǒ zhīdào dá'àn"],
      ["Can you help me?", "你能帮我吗？", "nǐ néng bāng wǒ ma?"],
    ],
  },
  d123: {
    vocab: [
      ["who", "谁", "shéi"],
      ["what", "什么", "shén me"],
      ["where", "哪里", "nǎ lǐ"],
      ["when", "什么时候", "shén me shí hou"],
      ["why", "为什么", "wèi shén me"],
      ["how", "怎么", "zěn me"],
      ["which", "哪个", "nǎ ge"],
      ["how much", "多少钱", "duō shǎo qián"],
    ],
    phrases: [
      ["Where is the station?", "车站在哪里？", "chēzhàn zài nǎlǐ?"],
      ["How much does it cost?", "这个多少钱？", "zhège duōshǎo qián?"],
    ],
  },
  d131: {
    vocab: [
      ["my", "我的", "wǒ de"],
      ["your", "你的", "nǐ de"],
      ["his", "他的", "tā de"],
      ["her", "她的", "tā de"],
      ["our", "我们的", "wǒ men de"],
      ["their", "他们的", "tā men de"],
      ["mine", "我的", "wǒ de"],
      ["yours", "你的", "nǐ de"],
    ],
    phrases: [
      ["This is my book", "这是我的书", "zhè shì wǒ de shū"],
      ["Is this your phone?", "这是你的手机吗？", "zhè shì nǐ de shǒujī ma?"],
    ],
  },
  d132: {
    vocab: [
      ["in", "里面", "lǐ miàn"],
      ["on", "上面", "shàng miàn"],
      ["under", "下面", "xià miàn"],
      ["next to", "旁边", "páng biān"],
      ["behind", "后面", "hòu miàn"],
      ["in front of", "前面", "qián miàn"],
      ["between", "中间", "zhōng jiān"],
      ["with", "和", "hé"],
    ],
    phrases: [
      ["The cat is on the table", "猫在桌子上", "māo zài zhuōzi shàng"],
      ["The park is next to my house", "公园在我家旁边", "gōngyuán zài wǒ jiā pángbiān"],
    ],
  },
  d133: {
    vocab: [
      ["today", "今天", "jīn tiān"],
      ["tomorrow", "明天", "míng tiān"],
      ["yesterday", "昨天", "zuó tiān"],
      ["now", "现在", "xiàn zài"],
      ["soon", "很快", "hěn kuài"],
      ["always", "总是", "zǒng shì"],
      ["never", "从不", "cóng bù"],
      ["often", "经常", "jīng cháng"],
    ],
    phrases: [
      ["I am busy now", "我现在很忙", "wǒ xiànzài hěn máng"],
      ["We will meet soon", "我们很快就会见面", "wǒmen hěn kuài jiù huì jiànmiàn"],
    ],
  },
  d141: {
    vocab: [
      ["fast", "快", "kuài"],
      ["slow", "慢", "màn"],
      ["strong", "强壮", "qiáng zhuàng"],
      ["weak", "弱", "ruò"],
      ["easy", "容易", "róng yì"],
      ["difficult", "难", "nán"],
      ["quiet", "安静", "ān jìng"],
      ["loud", "大声", "dà shēng"],
    ],
    phrases: [
      ["This exercise is easy", "这个练习很容易", "zhège liànxí hěn róngyì"],
      ["The rabbit is fast", "兔子很快", "tùzi hěn kuài"],
    ],
  },
  d142: {
    vocab: [
      ["tall", "高", "gāo"],
      ["short", "矮", "ǎi"],
      ["young", "年轻", "nián qīng"],
      ["beautiful", "漂亮", "piào liang"],
      ["rich", "有钱", "yǒu qián"],
      ["poor", "穷", "qióng"],
      ["thin", "瘦", "shòu"],
      ["strong", "强壮", "qiáng zhuàng"],
    ],
    phrases: [
      ["My brother is very tall", "我的哥哥很高", "wǒ de gēge hěn gāo"],
      ["She is young and beautiful", "她又年轻又漂亮", "tā yòu niánqīng yòu piàoliang"],
    ],
  },
  d143: {
    vocab: [
      ["kind", "善良", "shàn liáng"],
      ["friendly", "友好", "yǒu hǎo"],
      ["funny", "有趣", "yǒu qù"],
      ["serious", "严肃", "yán sù"],
      ["lazy", "懒惰", "lǎn duò"],
      ["hardworking", "勤奋", "qín fèn"],
      ["honest", "诚实", "chéng shí"],
      ["smart", "聪明", "cōng míng"],
    ],
    phrases: [
      ["My teacher is very kind", "我的老师很善良", "wǒ de lǎoshī hěn shànliáng"],
      ["He is funny and smart", "他又有趣又聪明", "tā yòu yǒuqù yòu cōngmíng"],
    ],
  },
  d151: {
    vocab: [
      ["help", "帮助", "bāng zhù"],
      ["danger", "危险", "wēi xiǎn"],
      ["police", "警察", "jǐng chá"],
      ["fire", "火", "huǒ"],
      ["accident", "事故", "shì gù"],
      ["hurt", "受伤", "shòu shāng"],
      ["emergency", "紧急情况", "jǐn jí qíng kuàng"],
      ["safe", "安全", "ān quán"],
    ],
    phrases: [
      ["I need help", "我需要帮助", "wǒ xūyào bāngzhù"],
      ["Call the police", "报警", "bàojǐng"],
    ],
  },
  d152: {
    vocab: [
      ["phone", "手机", "shǒu jī"],
      ["computer", "电脑", "diàn nǎo"],
      ["internet", "网络", "wǎng luò"],
      ["message", "消息", "xiāo xi"],
      ["screen", "屏幕", "píng mù"],
      ["battery", "电池", "diàn chí"],
      ["password", "密码", "mì mǎ"],
      ["download", "下载", "xià zǎi"],
    ],
    phrases: [
      ["The battery is low", "电池快没电了", "diànchí kuài méi diàn le"],
      ["I send you a message", "我给你发消息", "wǒ gěi nǐ fā xiāoxi"],
    ],
  },
  d153: {
    vocab: [
      ["plan", "计划", "jì huà"],
      ["goal", "目标", "mù biāo"],
      ["dream", "梦想", "mèng xiǎng"],
      ["maybe", "也许", "yě xǔ"],
      ["soon", "很快", "hěn kuài"],
      ["week", "周", "zhōu"],
      ["month", "月", "yuè"],
      ["will", "会", "huì"],
    ],
    phrases: [
      ["My dream is to travel", "我的梦想是去旅行", "wǒ de mèngxiǎng shì qù lǚxíng"],
      ["We will meet next week", "我们下周会见面", "wǒmen xiàzhōu huì jiànmiàn"],
    ],
  },
  d161: {
    vocab: [
      ["buy", "买", "mǎi"],
      ["sell", "卖", "mài"],
      ["price", "价格", "jià gé"],
      ["cheap", "便宜", "pián yi"],
      ["expensive", "贵", "guì"],
      ["size", "尺寸", "chǐ cùn"],
      ["pay", "付钱", "fù qián"],
      ["cash", "现金", "xiàn jīn"],
    ],
    phrases: [
      ["How much is this?", "这个多少钱？", "zhège duōshǎo qián?"],
      ["I will pay by card", "我用卡付钱", "wǒ yòng kǎ fùqián"],
    ],
  },
  d162: {
    vocab: [
      ["please", "请", "qǐng"],
      ["sorry", "对不起", "duì bu qǐ"],
      ["excuse me", "请问", "qǐng wèn"],
      ["wait", "等", "děng"],
      ["may I", "我可以吗", "wǒ kě yǐ ma"],
      ["let me", "让我", "ràng wǒ"],
      ["can you", "你能吗", "nǐ néng ma"],
      ["thank you", "谢谢", "xiè xie"],
    ],
    phrases: [
      ["Can you open the window?", "你能打开窗户吗？", "nǐ néng dǎkāi chuānghu ma?"],
      ["Excuse me, where is the exit?", "请问，出口在哪里？", "qǐngwèn, chūkǒu zài nǎlǐ?"],
    ],
  },
  d163: {
    vocab: [
      ["should", "应该", "yīng gāi"],
      ["try", "尝试", "cháng shì"],
      ["better", "更好", "gèng hǎo"],
      ["careful", "小心", "xiǎo xīn"],
      ["important", "重要", "zhòng yào"],
      ["remember", "记住", "jì zhù"],
      ["forget", "忘记", "wàng jì"],
      ["suggest", "建议", "jiàn yì"],
    ],
    phrases: [
      ["You should rest today", "你今天应该休息", "nǐ jīntiān yīnggāi xiūxi"],
      ["Remember to call me", "记得给我打电话", "jìde gěi wǒ dǎ diànhuà"],
    ],
  },
  d171: {
    vocab: [
      ["story", "故事", "gù shi"],
      ["day", "天", "tiān"],
      ["came", "来了", "lái le"],
      ["saw", "看见了", "kàn jiàn le"],
      ["went", "去了", "qù le"],
      ["met", "遇见了", "yù jiàn le"],
      ["before", "以前", "yǐ qián"],
      ["ago", "之前", "zhī qián"],
    ],
    phrases: [
      ["Yesterday I met my friend", "昨天我遇见了我的朋友", "zuótiān wǒ yùjiàn le wǒ de péngyǒu"],
      ["I went to the market", "我去了市场", "wǒ qù le shìchǎng"],
    ],
  },
  d172: {
    vocab: [
      ["birthday", "生日", "shēng rì"],
      ["party", "派对", "pài duì"],
      ["gift", "礼物", "lǐ wù"],
      ["cake", "蛋糕", "dàn gāo"],
      ["candle", "蜡烛", "là zhú"],
      ["celebrate", "庆祝", "qìng zhù"],
      ["invitation", "邀请", "yāo qǐng"],
      ["holiday", "假期", "jià qī"],
    ],
    phrases: [
      ["Happy birthday!", "生日快乐！", "shēngrì kuàilè!"],
      ["We celebrate with a party", "我们开派对庆祝", "wǒmen kāi pàiduì qìngzhù"],
    ],
  },
};